### ISSUE TITLE
Tweet de soutien à LQDN pour leur campagne de dons

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/besogne#1]
Nous avons une bannière sur notre site pour soutenir LQDN et les aider à boucler leur campagne de dons pour assurer le budget 2016.

Je propose que nous tweetions aussi notre soutien en utilisant ce lien https://soutien.laquadrature.net/?from=mozfr

Il faudrait rédiger un tweet, j'ai pas trop le temps aujourd'hui, toute aide est la bienvenue. On peut discuter du texte dans ce ticker.

**Comment by Mozinet-fr** [comment]
.@Mozilla et @laquadrature ont eu des luttes communes cette année. La communauté francophone vous appelle à donner à https://soutien.laquadrature.net/?from=mozfr

140 caractères

**Comment by pascalchevrel** [comment]
Il faut peut-être avoir une petite marge de caractères pour les retweets? Sinon, j'aimerais qu'on mentionne si possible le mot "bénévoles" plutôt que communauté pour éviter toute ambigüité sur le fait que ce sont les bénévoles Mozilla qui font cet appel et pas Mozilla en tant qu'organisation.

**Comment by Mozinet-fr** [comment]
> Il faut peut-être avoir une petite marge de caractères pour les retweets?

Normalement plus depuis des années. Le retweet normal n'ajoute pas au tweet d'origine. Pour les retweets avec citation récemment mis en place par Twitter, c'est le commentaire qui est amputé du nombre de caractères nécessaire à ajouter le lien (automatiquement) à ce nouveau message.

> Sinon, j'aimerais qu'on mentionne si possible le mot "bénévoles" plutôt que communauté pour éviter toute ambigüité sur le fait que ce sont les bénévoles Mozilla qui font cet appel et pas Mozilla en tant qu'organisation.

Je pensais que communauté sans Mozilla tout de suite après suffisait.

.@Mozilla et @laquadrature ont eu des luttes communes cette année. Nous bénévoles les soutenons et appelons aux dons https://soutien.laquadrature.net/?from=mozfr

toujours 140 caractères

**Comment by pascalchevrel** [comment]
emballé c'est pesé, merci Mozinet :)
https://twitter.com/mozilla_fr/status/669880888541495297
