### ISSUE TITLE
article de Bill Mc Closkey sur le projet Quantum

### ISSUE THREAD

**Issue by ghost** [mozfr/besogne#102]
Pour compléter la traduction (déjà en pré-publication pour le le blog Bidouilleux) d'un premier article d'annonce sur le projet émergent **Quantum**
il serait intéressant de traduire au moins une bonne partie de cet autre article de Bill Mc Closkey
https://billmccloskey.wordpress.com/2016/10/27/mozillas-quantum-project/
Il explique un peu les 4 sous-projets et développe l'un d'eux le Quantum DOM

Le pad de traduction est ici
https://mypads.framapad.org/mypads/?/mypads/group/mozilla-private-ar5c279u/pad/view/quantum-mc-closkey-gazu7kg

**Comment by ghost** [comment]
Un petit up car sur cette traduction déjà bien entamée il reste tout de même 5 ou 6 paragraphes à traduire qui nécessitent **des connaissances techniques** que je n'ai pas. 
Appel donc aux bonnes volontés compétentes !

**Comment by Mozinet-fr** [comment]
@goofy-bz peut-être relancer la liste ? Je ne crois pas que beaucoup de monde suive le GitHub en continu…

**Comment by ghost** [comment]
FYI avancée et fin de la trad grâce à Jérémie et julien : je passe l'article dans le blog, publication probable demain dans la matinée

**Comment by Mozinet-fr** [comment]
résultat : Le projet Quantum de Mozilla, des ambitions et des précisions - Bidouilleux d'Web https://tech.mozfr.org/post/2016/10/28/Le-projet-Quantum-de-Mozilla-%3A-des-ambitions-et-des-precisions
