### ISSUE TITLE
Rediriger wiki.mozfr.org vers https://github.com/mozfr/besogne/wiki

### ISSUE THREAD

**Issue by SphinxKnight** [mozfr/besogne#104]
La migration du wiki ayant été effectuée, serait-il possible d'appliquer une redirection pour éviter les ambiguïtés ? 
Merci :))

**Comment by lhirlimann** [comment]
cahngemanet de cname de wiki vers gandi. reload du dns .

**Comment by pascalchevrel** [comment]
htaccess de redirection mis en place

**Comment by SphinxKnight** [comment]
Thx @lhirlimann @pascalchevrel
