### ISSUE TITLE
404 pour l'image de soutien à La Quadrature en page d'accueil

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#105]
Sûrement dû au lancement d'un [nouveau site](https://soutien.laquadrature.net/) pour une nouvelle campagne de soutien, l'ancienne bannière de soutien à La Quadrature du Net renvoie une erreur 404 https://soutien.laquadrature.net/static/images/support_lqdn_250_B_fr.png et est donc absente de la [page d'accueil](https://mozfr.org/).

**Comment by TheoChevalier** [comment]
À la limite, on peut remettre l’ancienne : https://web.archive.org/web/20160829024400im_/https://soutien.laquadrature.net/static/images/support_lqdn_250_B_fr.png
Je ne vois pas d’image au même format sur cette page https://soutien.laquadrature.net/material

**Comment by Mozinet-fr** [comment]
[Moz-fr] [Soutien à La Quadrature du Net](http://listes.mozfr.org/pipermail/moz-fr/2016-November/009151.html)

**Comment by Mozinet-fr** [comment]
J'ai du spam régulier, ce serait sympa de fermer ce mailman.

**Comment by MatonAnthony** [comment]
@Mozinet, je pense que tu devrais ouvrir un nouveau bug et préciser à quel mailman tu fais référence.

**Comment by Mozinet-fr** [comment]
oups, erreur d'issue :flushed:

**Comment by lhirlimann** [comment]
L'image n'est pas disponible sur l'ancient serveur ....
