### ISSUE TITLE
Traduction de https://blog.mozilla.org/opendesign/arrival/

### ISSUE THREAD

**Issue by SphinxKnight** [mozfr/besogne#115]
Allez hop un nouveau logo, une nouvelle trad : https://mensuel.framapad.org/p/arrival-mozopen
Article original : https://blog.mozilla.org/opendesign/arrival/

**Comment by Mozinet-fr** [comment]
tu m'a doublé. J'étais en train de rédiger le pad.

NB : le début est traduit par l'agence.

**Comment by Mozinet-fr** [comment]
Pourquoi un pad temporaire ?

**Comment by SphinxKnight** [comment]
une fois traduit et publié, je ne vois pas trop l'intérêt de garder ça et d'encombrer framapad.
Le début déjà traduit est dispo quelque part ?

**Comment by Mozinet-fr** [comment]
sur mon pad :D

**Comment by SphinxKnight** [comment]
askip c'est publié : https://blog.mozfr.org/post/2017/01/arrivee-Mozilla-nouveau-logo
