### ISSUE TITLE
Article : key signing party

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#120]
Usul sur Twitter mentionne une _key signing party_ qui s'est tenue au FOSDEM l'an dernier (la nouvelle édition approche).

Un petit article présentant cette pratique de réunion en personne, incarné et de vulgarisation serait bien.

Voir [Carte Trello dans Communication](https://trello.com/c/qtIjVsMH).

**Comment by lhirlimann** [comment]
this is long done.
