### ISSUE TITLE
Lister Firefox Focus dans le menu latéral

### ISSUE THREAD

**Issue by TheoChevalier** [mozfr/besogne#122]
On liste Firefox pour iOS sur l’accueil, mais pas Firefox Focus https://itunes.apple.com/fr/app/id1055677337

Logo: 
![focus-firefox](https://cloud.githubusercontent.com/assets/1294206/22986006/1bfe8564-f3a2-11e6-8de7-5124ea93313f.png) https://support.mozilla.org/html/assets/focus-firefox.png

**Comment by Mozinet-fr** [comment]
En fait, c'est dans le menu latéral commun, non ?

**Comment by TheoChevalier** [comment]
Dans le même temps,  ce serait probablement l’occasion de mettre à jour l’icône de Firefox pour iOS avec l’icône utilisée sur SUMO, probablement plus parlante que l’icône iTunes.

![firefox-ios](https://cloud.githubusercontent.com/assets/1294206/22986125/7240e4bc-f3a2-11e6-8fc0-433e09c573cb.png)
 https://support.mozilla.org/html/assets/firefox-ios.png

**Comment by lhirlimann** [comment]
firefox ios est à jour. On utilise quoi comme liens pour focus ios/android , on met 2 icones ?

**Comment by lhirlimann** [comment]
les icones de focus sont dans https://github.com/mozfr/www/pull/132

**Comment by lhirlimann** [comment]
https://github.com/mozfr/www/pull/134
