### ISSUE TITLE
Le blog firefox OS est très haut dans la SEO lié à mozfr

### ISSUE THREAD

**Issue by MatonAnthony** [mozfr/besogne#123]
Le blog firefox OS est très haut dans la SEO lié à mozfr ce qui peut potentiellement impacter sur la qualité de nos visites, le projet étant mort.

Il me semble intéressant d'envisager de demander à Google de stopper le référencement de ce domaine et de le laisser s'enfouir dans les limbes de l'Internet afin de ne pas remuer le couteau dans la plaie et de ne pas susciter d'espoir ou d'interrogations sur Firefox OS :RIP:

Cette requête renvoie par exemple le blog firefox OS en 4ème résultat
https://www.google.fr/search?q=blog+mozfr&ie=utf-8&oe=utf-8&client=firefox-b-ab&gfe_rd=cr&ei=VIGYWJyfBfLS8AeC-q7oDA
Celle-ci le renvoie aussi très haut
https://www.google.be/search?q=Blog+mozilla+francophone&ie=utf-8&oe=utf-8&client=firefox-b-ab&gfe_rd=cr&ei=QOuZWL63Gq3H8AfBhaTgAw

**Comment by Mozinet-fr** [comment]
Le plan d'extinction de la communication Firefox OS prévoit de changer l'URL du blog (comme le titre en a été changé) pour qu'il ne contienne plus la marque « Firefox », mais on n'a jamais eu/pris le temps de le faire.

J'ai passé ledit blog en : Je souhaite que mon blog ne soit ni indexé ni archivé par les moteurs de recherche et archiveurs.
=> `<meta name="ROBOTS" content="NOINDEX, NOFOLLOW, NOARCHIVE" />`

**Comment by Mozinet-fr** [comment]
Ce n'est plus le cas au vu de quelques recherches.
