### ISSUE TITLE
Traduction de la position de Mozilla sur la réforme du droit d’auteur

### ISSUE THREAD

**Issue by TheoChevalier** [mozfr/besogne#124]
L’équipe Net Policy voudrait faire traduire en français un document à diffuser en priorité aux participants de la[ soirée sur la réforme du droit d’auteur](https://blog.mozfr.org/post/2017/01/Salle-comble-reforme-droit-auteur-21e-siecle) qui a eu lieu au bureau de Paris le mois dernier. Le document résume la position de Mozilla par rapport à la proposition de la Commission européenne pour la réforme du droit d’auteur. Si vous avez un peu de temps libre ce weekend, votre aide est la bienvenue :)

Le pad : https://mypads.framapad.org/p/copyright-mozilla-8qgjf7fg

Si il y a des passages où l’on a des doutes, je demanderai des précisions à Reagan ou à d’autres personnes de l’équipe, au besoin. Je vous propose donc d’ajouter des commentaires sur les passages où vous traduisez mais que vous avez un doute.

**Comment by Mozinet-fr** [comment]
Dans la barre d'outils du pad, tu as une URL plus directe https://mypads.framapad.org/p/copyright-mozilla-8qgjf7fg sauf s'il y a un problème…

**Comment by TheoChevalier** [comment]
Bien vu, merci. Je pensais qu’on ne pouvait avoir cette vue qu’avec le bouton pour agrandir…
Un problème à quel niveau ?

**Comment by Mozinet-fr** [comment]
de l'élision :p

**Comment by TheoChevalier** [comment]
Ok, j’essaierai d’y penser la prochaine fois 👍

**Comment by Mozinet-fr** [comment]
1er jet achevé

**Comment by popzelife** [comment]
Voilà une 1ière relecture effectuée. Il y a des propositions pour reformuler certaines phrases

**Comment by TheoChevalier** [comment]
Merci à tous les deux ! :)

**Comment by TheoChevalier** [comment]
Si jamais on veut publier ça aussi sur le blog, on a l’autorisation

**Comment by Mozinet-fr** [comment]
Tu leur as fourni une version définitive ?

**Comment by TheoChevalier** [comment]
Non pas encore

**Comment by Mozinet-fr** [comment]
@TheoChevalier des nouvelles ? une échéance ?

**Comment by TheoChevalier** [comment]
Salut, j’ai envoyé cette version, en espérant ne pas avoir fait de bêtises : https://docs.google.com/document/d/1YLxwUVWqFNPwQIHUNlSb_YANbscww-jnsWOitb6TxCs/edit
Reagan devrait faire la relecture finale, je vous tiens au courant dès que c’est fait :)

**Comment by Mozinet-fr** [comment]
Juste deux détails :

1er « (article » avec une majuscule fautive (pas les autres) ;

« rendre accessible des contenus protégés » => accessibles.

**Comment by TheoChevalier** [comment]
Merci, corrigé.
Reagan m’a envoyé des modifications de dernière minute dans la VO, j’ai appliqué les changements dans la VF.
Il reste juste celle-ci pour laquelle je ne suis pas sûr :
> Mozilla proposes to include a new exception to allow a natural person to use a work, or other subject matter, in its original form or in the creation of a new work.

Mozilla propose d’inclure une nouvelle exception qui permette à une personne physique d’utiliser une œuvre dans sa forme d’origine ou dans la création d’une nouvelle œuvre. 


> Mozilla proposes to include a new exception to allow a natural person to use a work, or other subject matter, in the creation of a new work or other subject-matter.

**Comment by popzelife** [comment]
> Mozilla propose d’inclure une nouvelle exception qui permette à une personne physique d’utiliser une œuvre dans sa forme d’origine ou dans la création d’une nouvelle œuvre et ses formes dérivées.

Enfin c'est ça l'idée mais la formulation n'est pas géniale, et je trouve pas mieux.

**Comment by TheoChevalier** [comment]
Désolé, j’ai pas actualisé mon commentaire, mais j’ai mis dans le doc :
> Mozilla propose d’inclure une nouvelle exception qui permette à une personne physique d’utiliser une œuvre ou d’autres objets protégés, lors de la création d’une nouvelle œuvre ou d’autres objets protégés.

subject-matter doit être traduit par « objets protégés », Pierre a trouvé une source fiable ici http://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:52016PC0596

**Comment by Mozinet-fr** [comment]
@TheoChevalier on pourra publier quand ?

**Comment by TheoChevalier** [comment]
J’attends la réponse de Reagan pour savoir si elle va modifier la traduction ou non, donc on pourra sûrement publier rapidement

**Comment by TheoChevalier** [comment]
On peut publier si on veut

**Comment by Mozinet-fr** [comment]
@TheoChevalier tu as la version finale quelque part ?

**Comment by TheoChevalier** [comment]
@Mozinet-fr la version du GDoc est la version finale :) Si tu fais référence à la version avec le joli design, je ne l’ai pas encore reçue

**Comment by Mozinet-fr** [comment]
@TheoChevalier ok, je la prends. On utilisera la belle version pour en remettre une couche :)

**Comment by Mozinet-fr** [comment]
➡️ [Mozilla face à la proposition de la Commission sur le droit d’auteur dans le marché unique numérique](https://notreinternet.mozfr.org/post/2017/02/Mozilla-face-proposition-commission-droit-auteur-marche-unique-numerique) - Mozilla et la vie publique

**Comment by TheoChevalier** [comment]
Voici les jolis PDF :

[moz_whitePaper_copyright_print_french_color_2.0.pdf](https://github.com/mozfr/besogne/files/879761/moz_whitePaper_copyright_print_french_color_2.0.pdf)
[moz_whitePaper_copyright_print_french_bw_2.0.pdf](https://github.com/mozfr/besogne/files/879759/moz_whitePaper_copyright_print_french_bw_2.0.pdf)
[moz_whitePaper_copyright_digital_french_color_2.0.pdf](https://github.com/mozfr/besogne/files/879760/moz_whitePaper_copyright_digital_french_color_2.0.pdf)
[moz_whitePaper_copyright_digital_french_bw_2.0.pdf](https://github.com/mozfr/besogne/files/879762/moz_whitePaper_copyright_digital_french_bw_2.0.pdf)

**Comment by TheoChevalier** [comment]
La version hébergée sur le site changecopyright: https://changecopyright.org/pdfs/moz_whitePaper_copyright_digital_french_color_2.0.pdf

**Comment by Mozinet-fr** [comment]
@TheoChevalier c'est fini ?

**Comment by TheoChevalier** [comment]
oui
