### ISSUE TITLE
Comm : créer un bridge entre Telegram et IRC

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#125]
À la dernière [réunion comm](https://mypads.framapad.org/p/7e-reunion-comm-mozfr-fr3ps7ld), il a été admis que chacun devrait pouvoir utiliser IRC selon ses habitudes ou un messager comme Telegram pratique en mobilité pour accéder aux discussions de la communication communautaire.

**Comment by popzelife** [comment]
J'ai entendu parlé de matrix.org qui permet de centraliser (ou plutôt décentraliser) les discussions et créer des bridges entre services de comm. Il existe déjà un bridge pour IRC https://github.com/matrix-org/matrix-appservice-irc et aussi pour Telegram https://github.com/matrix-org/matrix-appservice-tg

**Comment by MatonAnthony** [comment]
Teleirc (https://github.com/FruitieX/teleirc) semble être l'outil le plus utilisé.

La question la plus "épineuse", c'est d'installer (ce qui n'est pas très compliqué) mais surtout de maintenir dans le temps un outil qui sera utilisé au final par 2-3 personnes.

Je ne suis pas certain que ce soit raisonnable que quelqu'un "perde" son temps à maintenir l'outil à jour si seulement 2-3 personnes l'utilisent.

Néanmoins, Reps utilise un outil similaire, je pense donc demander à l'équipe IT Participation, si on ne peut pas nous ajouter sur leur outil. (Si cela vous va).

**Comment by lhirlimann** [comment]
Bahbah on peut sans doute faire touner la chose sur mozfr.org je met @mgoessen  en copie, et on trouve un paquet debian qui va bien.

**Comment by lhirlimann** [comment]
https://gist.github.com/bembu/3e1c55c90050f2ec1830f7dd334d740e 
https://github.com/RITlug/teleirc/releases

**Comment by Mozinet-fr** [comment]
vu qu'IRC de Mozilla va fermer, je ferme
