### ISSUE TITLE
Traduction de "A cartoon intro to WebAssembly"

### ISSUE THREAD

**Issue by SphinxKnight** [mozfr/besogne#128]
Article original : https://hacks.mozilla.org/2017/02/a-cartoon-intro-to-webassembly/
Dossier de pads : https://mypads.framapad.org/mypads/?/mypads/group/webassembly-bkmn7u6/view
Pad de lexique : https://mypads.framapad.org/mypads/?/mypads/group/webassembly-bkmn7u6/pad/view/lexique-webassembly-vj1mn7be

Accord : https://twitter.com/linclark/status/837331448931704832

**Comment by goodengrish** [comment]
Bonjour, étant quelque peu nouveau dans l'équipe, je me permets de proposer mes traductions que vous trouverez sous le nom d'Adam sur le pad.

**Comment by SphinxKnight** [comment]
Billets en attente d'approbation sur Dotclear. Publication estimée pour ce week-end.

**Comment by SphinxKnight** [comment]
It's on https://tech.mozfr.org/post/2017/03/08/Une-introduction-cartoonesque-a-WebAssembly
