### ISSUE TITLE
Page Mozilla Paris sur le wiki

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#129]
Créer une page avec les infos sur Mozilla Paris à réutiliser pour tous les événements s'y déroulant.

**Comment by TheoChevalier** [comment]
De quel genre d’informations a-t-on besoin, et à qui cette page s’adresserait ?

**Comment by Mozinet-fr** [comment]
J'ai créé une page avec les infos du Locasprint. C'est une page avec les infos pour nos événements communautaires que l'on peut lier dans chaque page ou article (voire copier-coler) avec un peu plus d'infos que la page en anglais de Mozilla.org.

https://github.com/mozfr/besogne/wiki/Se-rendre-%C3%A0-Mozilla-Paris

**Comment by Mozinet-fr** [comment]
Avait été faite : https://github.com/mozfr/besogne/wiki/Se-rendre-%C3%A0-Mozilla-Paris
