### ISSUE TITLE
Expiration certificat SSL *.mozfr.org 12/05 : renouvellement ou lets encrypt ?

### ISSUE THREAD

**Issue by mgoessen** [mozfr/besogne#131]
Bonjour,  Le certificat SSL de *.mozfr.org expire le 12/05, dans ~ 3 semaines donc.
Il faudrait que l'on voit ce que l'on fait d'ici là.  Deux solutions:

 * Passer à un ensemble de certificats Lets Encrypt.
    * Avantages: gratuit , prochaine renouvellements automatiques, soutient à letsencrypt
    * Inconvénients: un certificat par site (+ de 15 certificats requis), prise en main de lets encrypt

* Renouveller certificat *.mozfr.org chez gandi
   * Avantages: procédure connue, simple (10 mins chrono), un seul et unique certificat
   * Invoncénients: payant. 120€ HT prix public 90€ HT prix négocié (grille E) via https://www.gandi.net/soutient/

**Comment by mgoessen** [comment]
Personnelement,
* Je serais plus pour concerver un certificat gandi cette année. 
   * Manque de temps personnel pour suivre cela
   * Pas envie d'avoir des pannes
* En parallèle, prendre le temps de tester lets encrypt sur de plus petits sites moins critiques (womoz.org ?) afin de pouvoir le prévoir pour l'an prochain et être près
* À moins que quelqu'un se sente de faire cette migration d'ici là et de la suivre dans le temps.

Qu'en pensez vous ?

**Comment by TheoChevalier** [comment]
Je pense qu’on a pas vraiment le choix, on ne pourra pas se le faire payer par Mozilla cette fois-ci, et je ne préfère pas que l’un d’entre-nous se sente obligé de payer de sa poche.

Je pense qu’on doit se jeter à l’eau :) Et tant que l’autre n’est pas expiré, on doit pouvoir revenir facilement dessus quelques heures le temps de corriger l’install let’s encrypt si besoin ?

**Comment by laurentj** [comment]
> Inconvénients: un certificat par site (+ de 15 certificats requis), 

En quoi est-ce un inconvénient ?

> prise en main de lets encrypt

Il n'y a rien de compliqué. Je peux même "libérer" quelques scripts maison qui sont beaucoup plus leger que le client officiel (et qui évitent de faire un shutdown du serveur le temps d'un renouvellement). Utilisé en prod depuis plusieurs mois sans aucun souci...

**Comment by lhirlimann** [comment]
Libère

Le 26 avr. 2017 10:10, "Laurent Jouanneau" <notifications@github.com> a
écrit :

Inconvénients: un certificat par site (+ de 15 certificats requis),

En quoi est-ce un inconvénient ?

prise en main de lets encrypt

Il n'y a rien de compliqué. Je peux même "libérer" quelques scripts maison
qui sont beaucoup plus leger que le client officiel (et qui évitent de
faire un shutdown du serveur le temps d'un renouvellement). Utilisé en prod
depuis plusieurs mois sans aucun souci...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mozfr/besogne/issues/131#issuecomment-297282722>, or mute
the thread

**Comment by laurentj** [comment]
Voilà, libération effectuée : https://github.com/innophi/ansible-letsencrypt ;-)

Tout est installé/configuré sur le serveur de mozfr.org.

Reste à créer maintenant les certificats pour chaque site. https://planete.mozfr.org est le premier à y être passé.

La procédure en gros :

- dans le virtualhost du port 80, on inclus quelques snippets (et on enleve les redirections existantes)

```
    Include snippets/letsencrypt_challenge.conf
    Include snippets/letsencrypt_redirect80.conf
```
et faire un `sudo service apache2 reload`

- on génère la Certificat Signing Request (csr), à ne faire qu'une fois pour toute pour chaque certificat (avec le user letsencrypt !):

```
sudo -u letsencrypt letsencrypt_preparekeys.sh planete.mozfr.org "/C=FR/ST=France/L=Paris/O=MozFr" planet.mozfr.org
```

- on peut maintenant génèrer le certificat. ça va appeler let's encrypt, qui va interroger notre serveur etc..

```
sudo -u letsencrypt letsencrypt_generate.sh planete.mozfr.org
```

- enfin, il faut modifier le virtualhost ssl (seulement après avoir généré le certificat sinon le serveur ne va pas redémarrer !). On remplace le snippet ssl-mozfr.conf par :

```
    Include snippets/ssl-letsencrypt.conf
    SSLCertificateFile /var/lib/letsencrypt/certs/planete.mozfr.org.crt
    SSLCertificateKeyFile /var/lib/letsencrypt/private/planete.mozfr.org.key
```

Après un  `sudo service apache2 reload`, vous devriez voir le certificat let's encrypt dans Firefox.

Et on ne touche plus à rien. Un cron (appartenant à letsencrypt) est lancé tous les jours : il vérifie chaque certificat, et regénère ceux qui ne vont plus être valides (ceux qui ont moins de 15 jours avant la date butoir).

Je modifierais les autres sites plus tard

**Comment by laurentj** [comment]
bugzilla, firefoxos, blog : done

**Comment by mgoessen** [comment]
Salut,

Merci BEAUCOUP laurentj pour le boulot.

>> Inconvénients: un certificat par site (+ de 15 certificats requis),
> En quoi est-ce un inconvénient ?
> [...]
> Je modifierais les autres sites plus tard

Je crois que depuis tu as deviné ;-)

Merci en tout cas :)

**Comment by laurentj** [comment]
Tous les sites ont maintenant un certificat ssl let's encrypt :-)

**Comment by TheoChevalier** [comment]
Merci @laurentj c’est vraiment cool \o/

Il reste les ML https://listes.mozfr.org/mailman/listinfo/moz-fr mais elles sont encore sur l’ancien serveur :/

**Comment by pascalchevrel** [comment]
\o/ :)
