### ISSUE TITLE
Requestining localization for Strategy Survey e-mail

### ISSUE THREAD

**Issue by couci** [mozfr/besogne#132]
Hello,
@Flore-mozfr that this is the best place to request a translation for the francophone community.

I would like to translate the e-mail  text from the Strategic Survey. Context can be found here: https://docs.google.com/document/d/1UHTZ7ziXbCHiF0JgfMXSmBoIeLtmyP6VUHrVgYgdRQw/edit

This will be sent localised to the mozilla francophone list along with the localized survey.

thanks!

**Comment by TheoChevalier** [comment]
Hi @couci, thanks for filling this issue. This is indeed an appropriate place, the Mozilla Localizations product + French / fr component on Bugzilla would have worked, too.

I can’t personally commit to this translation until at least a week or so as we have higher priority translations to deal with (Photon UX, Paperstorm…), but I’m sure someone will be able to jump in

**Comment by couci** [comment]
thanks a lot for the reply @TheoChevalier

**Comment by TheoChevalier** [comment]
This has been posted yesterday http://listes.mozfr.org/pipermail/moz-fr/2017-May/009360.html
