### ISSUE TITLE
Ajouter la chaine youtube sur la page de garde :)

### ISSUE THREAD

**Issue by lhirlimann** [mozfr/besogne#134]

**Comment by Mozinet-fr** [comment]
Il faut aussi le logo de YouTube en CSS, il me semble.

**Comment by lhirlimann** [comment]
On 14/05/2017 13:47, Mozinet wrote:
>
> Il faut aussi le logo de YouTube en CSS, il me semble.
>
Une idée de l'endroit où je peux trouver le logo à la bonne taille, au
bon format ?

-- 
https://www.hirlimann.net/Ludovic/carnet/

**Comment by lhirlimann** [comment]
trouvé le logo à https://www.youtube.com/yt/brand/downloads.html et je l'ai donsize avec imagemagick :)

**Comment by lhirlimann** [comment]
PR pending merge
