### ISSUE TITLE
Problèmes mailman

### ISSUE THREAD

**Issue by TheoChevalier** [mozfr/besogne#138]
Probablement lié aux problèmes qu’on a eu sur diplo récemment, mais l’interface d’admin, la page d’abonnement et les archives des mailing lists ne sont pas accessibles :/

**Comment by TheoChevalier** [comment]
Les messages ne sont visiblement pas envoyés sur la mailing list, quelqu’un pourra regarder la semaine prochaine ? J’ai vraiment besoin de lancer cet appel à traduction.
J’ai tenté de redémarrer des trucs mais visiblement ça ne fait rien…

**Comment by barzogh** [comment]
Je l'ai bien reçu bier cet appel pourtant..

**Comment by Mozinet-fr** [comment]
J'ai rien reçu. J'ai vérifié le spam, rien.

**Comment by Mozinet-fr** [comment]
Sur la [page d'archive](https://listes.mozfr.org/mailman/listinfo/moz-fr/),  j'ai une erreur de sécurité : « listes.mozfr.org utilise un certificat de sécurité invalide. Le certificat a expiré le 18 avril 2016 à 01:59. La date courante est 8 juillet 2017 à 10:22. Code d’erreur : SEC_ERROR_EXPIRED_CERTIFICATE » puis, quand on accepte le certificat, on tombe sur une page d'erreur 404.

**Comment by TheoChevalier** [comment]
L’erreur de certificat n’est pas liée, on a pas Let’s Encrypt sur le serveur des mailing list et le certificat Gandi a expiré. Ce sera résolu lorsque les mailing list seront migrées sur le nouveau serveur. La 404 en revanche est liée, le service ne doit pas tourner, mais ça n’en dit pas beaucoup sur les raisons de la panne.

**Comment by Mozinet-fr** [comment]
C'est pas justement ce que dit l'erreur : que le certificat a expiré, et donc que le service ne peut tourner avec sa configuration actuelle sans certificat valide ?

**Comment by TheoChevalier** [comment]
Rien ne l’indique spécifiquement en tout cas.

Une piste : https://pastebin.mozilla.org/9026712 si ces erreurs n’étaient pas présentes avant, c’est peut-être que quelqu’un a lancé un chroot www-data sur /var récemment ?

**Comment by SphinxKnight** [comment]
C'est tout bon désormais ? :)

**Comment by TheoChevalier** [comment]
Oui ! on a oublié de fermer le ticket :)
