### ISSUE TITLE
Suppression des liens vers les communautés "francophones" dans la sidebar

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/besogne#14]
L'idée de faire de MozFR la communauté francophone qui fédérerait les autres communautés francophones d'Afrique notamment est initialement généreuse mais si on regarde les faits avec 4 ans :
- la moitié des sites listés dans notre barre latérale sont en 404, ces communautés n'existent plus ou  n'ont eu qu'une existence temporaire
- certains sont des sites exclusivement en arabe, quel rapport avec la francophonie ?
- aucune de ces communautés ne participe à MozFr, il y a des bénévoles de ces régions qui participent à MozFR mais qui n'ont aucun contact ni affiliation avec ces entités régionales

A minima, il faudrait ne conserver que les liens actifs et réellement francophones, donc en fait Mozilla Belgique (même si la dernier nouvelle est de 2014…) et Mozilla Tunisia. le reste devrait juste être supprimé.

**Comment by Flore-mozfr** [comment]
Je suis d'accord avec toi, tous les francophones sont bienvenus à mozfr, forcément, mais autant concentrer nos efforts vers les communautés régionales qui participent réellement en français.

**Comment by MatonAnthony** [comment]
C'est fait merci @SphinxKnight !
