### ISSUE TITLE
Traduction Firefox Roadmap for Flash End-of-Life

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#141]
Je vous propose de traduire le billet du blog *Future Releases* de Mozilla de Benjamin Smedberg : [Firefox Roadmap for Flash End-of-Life](https://blog.mozilla.org/futurereleases/2017/07/25/firefox-roadmap-flash-end-life/) (25 juil. 2017)

Pad de traduction : https://mypads.framapad.org/p/firefox-roadmap-for-flash-end-of-life-f0wex73i

**Comment by c0depr1sm** [comment]
Mozinet, David_5.1 avaient déjà bien avancé. J'ai ajouté un bout. On y est je crois 👍

**Comment by Mozinet-fr** [comment]
Merci à tous !

L'article a été publié hier soir : [Firefox, le Web et la fin de Flash](https://blog.mozfr.org/post/2017/07/Firefox-Web-fin-Flash) 

Pour vos réseaux : https://www.facebook.com/frmozilla/posts/1723654744331322

https://twitter.com/mozilla_fr/status/890320287811743744

https://mamot.fr/@Mozilla/3383944

Pour **les nouveaux** participants, si vous voulez qu'un lien – typiquement un compte Twitter ou d'un autre réseau, ou un blog – soit ajouté sous la mention de votre pseudo, merci de me l'indiquer ici ou en privé. Ce n'est pas obligatoire. Ça permet à un·e lecteur·rice intéressé·e de pouvoir découvrir la diversité des contributeurs.
