### ISSUE TITLE
Page PluginCheck sera désactivée. Retirer cette référence depuis les articles

### ISSUE THREAD

**Issue by c0depr1sm** [mozfr/besogne#142]
Bonjour, 
Une série d'articles SUMO appellent le [site de vérification des plugins Firefox](https://www.mozilla.org/plugincheck/) qui [sera déactivée](https://bugzilla.mozilla.org/show_bug.cgi?id=1277905) vraisemblablement vers le 10 août. Il faut donc enlever le lien sur nos articles SUMO fr. Voir l'annonce [en anglais et la discussion](https://support.mozilla.org/en-US/forums/knowledge-base-articles/712532)

Pour nous faciliter la vie, j'ai rassemblé depuis cette discussion une liste d'articles à corriger.
Soit ils utilisent un modèle qui sera inutile, soit ils font référence directement à la page de vérification. (Notez que j'ai déjà soumis pour vérification une modification du modèle qui le désactive).

Voici donc la liste des pages: 
- [x] (fait - à vérifier) [Utiliser les plugins pour écouter de la musique, voir des vidéos, jouer et plus encore](https://support.mozilla.org/fr/kb/utiliser-plugins-ecouter-voir-jouer/history)
- [x] (fait - à vérifier) (https://support.mozilla.org/fr/kb/modules-causent-problemes-liste-blocage/history)
- [x] (fait - validé) [Résoudre des problèmes de Firefox avec les plugins comme Flash ou Java](https://support.mozilla.org/fr/kb/resoudre-problemes-firefox-plugins/history)
- [x] (fait - validé) [Attention : le plugin ne répond pas – ce que cela signifie et le corriger](https://support.mozilla.org/fr/kb/attention-plugin-repond-pas/history)
- [x] (fait - validé)[Envoyer des rapports de plantage de plugin pour aider Mozilla à améliorer Firefox](https://support.mozilla.org/fr/kb/envoyer-rapports-plantage-plugin/history)
- [x] (fait) Pourquoi dois-je cliquer pour activer les plugins ?
- [x] [Corriger les problèmes audio et vidéo courants](https://support.mozilla.org/fr/kb/corriger-problemes-audio-video-courants/history)
- [x] [Firefox consomme trop de mémoire, y remédier](https://support.mozilla.org/fr/kb/firefox-consomme-trop-de-memoire-y-remedier/history)
- [x] (fait-à vérifier)) (https://support.mozilla.org/fr/kb/firefox-consomme-trop-processeur-corriger/history)
- [x] [Plugin Flash – le garder à jour et résoudre les problèmes](https://support.mozilla.org/fr/kb/plugin-flash-garder-jour-resoudre-problemes/history)
- [x] (fait-à vérifier) [Éviter les plantages – trucs et astuces](https://support.mozilla.org/fr/kb/eviter-plantages-trucs-astuces/history) 
- [x] [Le plugin Adobe Flash a planté – empêcher que cela se reproduise](https://support.mozilla.org/fr/kb/plugin-adobe-flash-plante/history) 
- [x] [Firefox plante – résoudre, prévenir et obtenir de l'aide](https://support.mozilla.org/fr/kb/firefox-plante-resoudre-prevenir-obtenir-aide/history)
- [x] [Rester protégé sur le Web](https://support.mozilla.org/fr/kb/rester-protege-sur-le-web/history)
- [x] [Plugin Flash – le garder à jour et résoudre les problèmes (pour Linux)](https://support.mozilla.org/fr/kb/plugin-flash-garder-jour-resoudre-problemes/history) 
- [x] [Résoudre des problèmes de Firefox causés par des logiciels malveillants](https://support.mozilla.org/fr/kb/resoudre-problemes-firefox-logiciels-malveillants/history)
- [x] (fait - validé) (https://support.mozilla.org/fr/kb/installer-plugin-flash-voir-videos-animations-jeux/history)
- [x] [Firefox se bloque ou ne répond pas – corriger cela](https://support.mozilla.org/fr/kb/firefox-bloque-repond-pas-corriger/history)

Aussi
- [x] (fait) Il faut enlever l'article [Réponse du forum - Vérification des plugins](https://support.mozilla.org/fr/kb/reponse-du-forum-verification-des-plugins)
- [x] (fait) Il faut enlever l'item "Vérifier un plugin" de la rubrique "Plugins" dans la liste [Réponse du forum](https://support.mozilla.org/fr/kb/reponses-communes-du-forum#w_plugins)

**Comment by Mozinet-fr** [comment]
J'ai approuvé le modèle plugincheck ce soir

**Comment by ghost** [comment]
merci beaucoup c0depr1sm 👍 pour cette liste très utile et pratique (comme on peut l'éditer on peut la tenir à jour sans encombrer le fil de discussion ici). J'ai commencé, n'hésitez pas à contribuer, c'est généralement assez rapide à faire (peu de modifs à effectuer)

**Comment by c0depr1sm** [comment]
Merci à tous les contributeurs qui ont complété cette jolie besogne à temps pour le retrait de la page plugincheck! Bravo!

**Comment by Mozinet-fr** [comment]
Donc je ferme l'issue. Super boulot, merci.
