### ISSUE TITLE
Traduction How Could You Use a Speech Interface?

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#144]
Je vous propose de traduire le billet du blog de Mozilla de Kelly Davis : [How Could You Use a Speech Interface?](https://blog.mozilla.org/blog/2017/07/28/machine-learning-speech-recognition/) (28 juil. 2017)

Pad de traduction : https://mypads.framapad.org/p/how-could-you-use-a-speech-interface-g71u1x74p

**Comment by c0depr1sm** [comment]
Pour une raison que je comprends pas, le mode edition du pad est bloqué, je ne vois plus qu'une page web sans capacité d'édition... pourtant il reste des coquilles à corriger...

**Comment by Mozinet-fr** [comment]
Merci à tous ceux qui ont participé. Résultat : Mozilla ouvre la voix https://blog.mozfr.org/post/2017/07/Mozilla-ouvre-la-voix-reconnaissance-vocale

Pour vos réseaux : https://twitter.com/mozilla_fr/status/892042043362562048

https://mamot.fr/@Mozilla/3492402

https://www.facebook.com/frmozilla/posts/1728667290496734
