### ISSUE TITLE
Francisation des images dans les articles SUMO fr (partie 1)

### ISSUE THREAD

**Issue by c0depr1sm** [mozfr/besogne#145]
Bonjour, 
Il s'agit de la francisation des images dans tous les articles SUMO en ordre de popularité.
Premier survol: Parmi les articles les plus lus des 30 derniers jours, un seul a besoin d'images francisées.
Ci-après, coché signifie pas d'image ou déjà francisé.

- [x] [Pourquoi dois-je cliquer pour activer les plugins ?](https://support.mozilla.org/fr/kb/pourquoi-cliquer-pour-activer-plugins)
- [x] (pas d'image)[Modernisation de la technologie des modules pour Firefox](https://support.mozilla.org/fr/kb/modernisation-technologie-modules-firefox)
- [ ] [Paramètres pour les polices, langues, fenêtres popup, images et JavaScript](https://support.mozilla.org/fr/kb/parametres-polices-langues-popup-javascript)
- [x] (pas d'image)[Gestion des profils dans Thunderbird](https://support.mozilla.org/fr/kb/profils-dans-thunderbird)
- [x] [Mettre à jour vos pilotes graphiques pour utiliser l'accélération graphique matérielle et WebGL](https://support.mozilla.org/fr/kb/mettre-jour-pilotes-graphiques)
- [x] (pas d'image)[Utiliser les plugins pour écouter de la musique, voir des vidéos, jouer et plus encore](https://support.mozilla.org/fr/kb/utiliser-plugins-ecouter-voir-jouer)
- [x] [Éditeur de configuration pour Firefox](https://support.mozilla.org/fr/kb/editeur-de-configuration-pour-firefox)
- [x] (pas d'image)[Utiliser le plugin Adobe Reader pour voir ou télécharger les fichiers PDF](https://support.mozilla.org/fr/kb/utiliser-plugin-adobe-reader-voir-telecharger-pdf)
- [x] [Les modules complémentaires qui causent des problèmes de stabilité ou de sécurité sont mis dans une liste de blocage](https://support.mozilla.org/fr/kb/modules-causent-problemes-liste-blocage) 
- [x] (pas d'image)[Ce qu'il faut faire si vous ne pouvez pas télécharger ou enregistrer les fichiers](https://support.mozilla.org/fr/kb/que-faire-pas-telecharger-enregistrer-fichiers) 
- [x] [Configuration automatique de compte](https://support.mozilla.org/fr/kb/configuration-automatique-de-compte)
- [x] (pas d'image)[Est-ce que Firefox fonctionnera sur mon appareil mobile ?](https://support.mozilla.org/fr/kb/est-ce-que-firefox-fonctionnera-sur-appareil-mobile)
- [x] (pas d'image)[Installer Firefox pour Android sur un Kindle Fire d'Amazon](https://support.mozilla.org/fr/kb/installer-firefox-pour-android-sur-un-kindle-fire-amazon) 
- [x] [Paramétrer Adobe Flash afin qu'il ne se lance qu'à la demande sous Firefox](https://support.mozilla.org/fr/kb/adobe-flash-demander-pour-activer-firefox)
- [x] (en révision)(pas d'image)[Comment empêcher Firefox d'établir automatiquement des connexions sans ma permission](https://support.mozilla.org/fr/kb/comment-empecher-firefox-etablir-automatiquement-connexions)
- [x] [Installation de Thunderbird sur Mac](https://support.mozilla.org/fr/kb/installation-thunderbird-mac)
- [x] [Changer les polices et couleurs que les sites web utilisent](https://support.mozilla.org/fr/kb/changer-polices-couleurs-sites-utilisent)
- [x] [Signature numérique et chiffrement des messages](https://support.mozilla.org/fr/kb/signature-numerique-et-chiffrement-des-messages)
- [x] [Installer une extension sur Thunderbird](https://support.mozilla.org/fr/kb/installer-une-extension-sur-thunderbird)

**Comment by c0depr1sm** [comment]
Un des obstacles avec la francisation des images c'est que les articles d'origine sont parfois désuets. Tant qu'à franciser, autant mettre à jour pour Fx55 et l'image en sera utile pour plus longtemps. :)

**Comment by Mozinet-fr** [comment]
Oui, ça demande du travail de recensement et d'analyse (vérifier aussi s'il n'y a pas de mise à jour de la version en-US qui n'aurait pas été traduite).

**Comment by Mozinet-fr** [comment]
Tâche réalisée
