### ISSUE TITLE
Traduction All Hands On Deck – How you can use your skills to contribute to Firefox 57 success

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#149]
Je vous propose de traduire le billet du blog *stream of bytes* de Zibi Braniecki “gandalf” : [All Hands On Deck – How you can use your skills to contribute to Firefox 57 success](https://diary.braniecki.net/2017/09/01/all-hands-on-deck-how-you-can-use-your-skills-to-contribute-to-firefox-57-success/) (1er sept. 2017)

Pad de traduction : https://mypads.framapad.org/p/all-hands-on-deck-firefox-57-success-1e11527c8

**Comment by pascalchevrel** [comment]
Je le mettrai sur about:home fr quand ce sera fait :)

**Comment by Mozinet-fr** [comment]
La traduction est publiée : [Firefox 57 : chacun peut contribuer à son succès](https://blog.mozfr.org/post/2017/09/Firefox-57-chacun-peut-contribuer-a-son-succes).

Merci à tous. Pour ceux qui ont mis leur pseudo dans le pad et qui veulent qu'on ajoute un lien vers un compte de réseaux sociaux ou un blog (ou ce qui les représente), dites-le moi.

Merci de partager sur vos propres réseaux :

https://mamot.fr/web/statuses/4433364
https://twitter.com/mozilla_fr/status/906572023501115392
https://www.facebook.com/frmozilla/posts/1767210936642369
