### ISSUE TITLE
Mise à jour des liens obsolètes dans la sidebar

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/besogne#15]
- Bonjourmozilla est mort depuis 1 an et demi, personne ne le reprend.
- le lien vers l'APK android est 404 et n'offre aucun intérêt
- il n'y a pas de lien vers Firefox pour iOS
- Frenchmozilla est mort depuis des années, garder un lien vers ce site c'est entretenir la confusion sur qui fait la localisation aujourd'hui, et depuis 2011 c'est MozFR
- la page 'autres" envoie vers une vieille page de téléchargement de Frenchmozilla qui propose des versions obsolètes des logiciels

Tout ça représente juste du bruit dans notre interface et par contre des blogs plus récents et avec du contenu intéressants comme celui de firefox os ou notreinternet ne sont pas eux listés.

Je mets ce ticket dans le tracker généraliste plutôt que dans le tracker du site web parce qu'il pose aussi des questions de stratégie.

**Comment by filip42** [comment]
+1 pour frenchmozilla, cela m'évitera de recevoir des mails sur le contact de la page frenchmozilla :)

**Comment by SphinxKnight** [comment]
https://github.com/mozfr/www/pull/102
