### ISSUE TITLE
Changer l'image de Firefox sur le sous-forum Firefox

### ISSUE THREAD

**Issue by Flore-mozfr** [mozfr/besogne#158]
Hello,
On a un très vieux logo comme image du sous-forum Firefox sur forums.mozfr.org
Logiquement, on devrait pouvoir le changer dans la partie admin du forum, sauf que je n'ai pas vraiment trouvé comment (pas de bouton parcourir, par exemple).
![capture d ecran 2017-11-21 a 21 40 57](https://user-images.githubusercontent.com/6987429/33095737-9f65a226-cefc-11e7-8eaf-5ef5db8501ea.png)
Une solution rapide pourrait être de mettre le nouveau logo de Firefox avec le nom utilisé par le forum.

Parce que ça fait pas super sérieux d'avoir un vieux logo sur le forum...

Merci

**Comment by TheoChevalier** [comment]
fait, merci @Flore-mozfr, je pensais que ça se faisait via l’admin du forum
