### ISSUE TITLE
Tâches pour les collectes de fonds 2017

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#159]
Création du projet [Collectes de dons](https://github.com/mozfr/besogne/projects/2) pour suivre les tâches et questions relatives aux collectes de fonds poussées ou envisagées par la communauté et leur mise en œuvre suite à la discussion entamée sur la liste.

_N'hésitez pas à commenter et à vous porter volontaire pour une ou plusieurs tâches._

### état actuel

- Depuis quelques années nous avons une bannière de soutien à _La Quadrature du Net_ sur notre [page d'accueil](https://mozfr.org)
- À la demande de participants au projet Tails, j'ai rédigé [un billet de blog](https://blog.mozfr.org/post/2017/11/Tails-a-besoin-de-vous) soulignant les liens de cette organisation avec Mozilla et nos valeurs communes

### suggestions

- [La Quadrature du Net](https://soutien.laquadrature.net/)
- Lors d'un des derniers événements, on m'a aussi suggéré de faire un article sur la collecte de dons du **projet Tor** que double Mozilla cette année.
- [Framasoft](https://soutenir.framasoft.org/)
- L'[April](https://april.org/campagne/) (est rigolo en plus)
- [Nos Oignons](https://nos-oignons.net/Donnez/index.fr.html) qui finance des nœuds Tor

### forme de chaque soutien

- billet de blog
- réseaux sociaux
- vidéo sur la chaîne
- posts dans les forums
- bannière

ou bandeau tournant pour toutes ou certaines des campagnes ?

### liens

Liste de discussion : [Partage de campagnes de financement d'organisations apparentées](https://listes.mozfr.org/pipermail/moz-fr/2017-November/009554.html)
Comm : [carte Trello : \[meta\] collectes de dons de fin d'année](https://trello.com/c/IT4GVlqY)

**Comment by Porkepix** [comment]
Les liens pour celle du Tor Project : https://donate.torproject.org/pdr
Et de Tails : https://tails.boum.org/donate/
