### ISSUE TITLE
Appel aux dons La Quadrature du Net

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#161]
Appel aux dons pour La Quadrature du Net et les Exégètes amateurs [à relire](https://docs.google.com/document/d/1loVFZg9tU__gz97IvcXjxm9LeLtPPdOaJVWeiKhz9Vg/edit?usp=sharing).

**Comment by Porkepix** [comment]
Pour info, bannière animée de la campagne de dons : https://www.laquadrature.net/files/soutien_francais_20171130.gif
Ou sans animation : https://www.laquadrature.net/files/soutien-2017-1-fr.png

**Comment by Mozinet-fr** [comment]
L'appel est publié : [Aidons La Quadrature du Net à protéger nos libertés](https://blog.mozfr.org/post/2017/12/Aidons-La-Quadrature-du-Net-a-proteger-nos-libertes "Aidons La Quadrature du Net à protéger nos libertés - Communauté Mozilla francophone")

et partagé sur les réseaux sociaux : 

- [Twitter](https://twitter.com/mozilla_fr/status/938833277238022145 "Mozilla francophone sur Twitter : La communauté Mozilla francophone appelle à donner à @LaQuadrature du Net pour l'aider à protéger nos libertés https://t.co/4kCoe9PtOa https://t.co/vfKukE4Nv1")
- [Mastodon](https://mamot.fr/@Mozilla/99134364759866454 "La communauté Mozilla francophone appelle à donner à @LaQuadrature du Net pour l'aider à protéger nos libertés – La Quadrature du Net – Mastodon – Media Fédéré")
- [Facebook](https://www.facebook.com/frmozilla/posts/1855440277819434 "La communauté Mozilla francophone appelle à donner à La Quadrature du Net pour l'aider à protéger nos libertés – Mozilla francophone")
