### ISSUE TITLE
Social login / openID pour forums.mozfr.org

### ISSUE THREAD

**Issue by tobozo** [mozfr/besogne#162]
Suite a [ce tweet](https://twitter.com/TobozoTagada/status/940525875841421312) @mozilla_fr m'a conseillé de créer un ticket ici.

Rendre l'authentification plus fluide lors de l'acces au forum pourrait permettre de recruter plus de répondant·e·s.

[Ce projet](https://github.com/oneall/social-login-phpbb) montre qu'une phpBB pas trop modifiée peut supporter l'authentification tierce.

**Comment by pascalchevrel** [comment]
je jette un œil là dessus, merci pour le pointeur

**Comment by pascalchevrel** [comment]
J'ai mis ça en place pour Facebook et Twitter il y a deux jours. Le process est assez lourd pour chaque service ajouté en fait. Si c'est stable et que ça ne pose pas de problème (notamment de spammeurs) on va garder ça. Merci pour le pointeur vers ce mod !

**Comment by tobozo** [comment]
youpi \o/

Sur le plus long terme ca aurait du sens d'ajouter le support github ?
Un "signup with github" compléterait le duo existant en permettant de mieux recouper les efforts de reporting d'une plateforme a l'autre.

[Github OAuth](https://developer.github.com/apps/building-oauth-apps/authorization-options-for-oauth-apps/)
[Exemple d'implémentation](https://developer.github.com/v3/guides/basics-of-authentication/)

**Comment by pascalchevrel** [comment]
c'est possible avec ce plugin mais je verrai plus tard :)
