### ISSUE TITLE
Traduction New Thunderbird Releases and New Thunderbird Staff

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#163]
Je vous propose de traduire le billet du blog de *Thunderbird* de Ryan Sipes : [New Thunderbird Releases and New Thunderbird Staff](https://blog.mozilla.org/thunderbird/2017/12/new-thunderbird-releases-and-new-thunderbird-staff/) (19 déc. 2017)

Pad de traduction : https://mypads.framapad.org/p/new-thunderbird-releases-and-new-staff-gh2c1l7xd

**Comment by fwhcat** [comment]
j'ai fait cque j'ai pu avant ma réunion ^^

**Comment by ghost** [comment]
traduction terminée mais à relire et vérifier.

**Comment by Mozinet-fr** [comment]
Merci à tous, le billet est en ligne : [Thunderbird : nouvelles versions et nouvelle équipe](https://blog.mozfr.org/post/2017/12/Thunderbird-nouvelles-versions-equipe)

Annonce réseaux sociaux :

https://twitter.com/mozilla_fr/status/944242610750869509
https://www.facebook.com/frmozilla/posts/1871530479543747
https://mamot.fr/@Mozilla/99218888537084479
