### ISSUE TITLE
Ecriture inclusive dans les traductions de MDN web docs

### ISSUE THREAD

**Issue by DavidLibeau** [mozfr/besogne#166]
Bonjour,
Je voudrais savoir si l'écriture inclusive est conseillé pour les traductions ?
Si oui, quel caractère est utilisé ? `.`, `·` ... ?
Merci

**Comment by SphinxKnight** [comment]
Les règles stylistiques générales sont définies ici : https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Writing_style_guide#Gender-neutral_language 

En ce qui concerne la traduction, ces règles s'appliquent également.

Le registre de MDN, technique, ainsi que l'absence de contrainte en longueur font qu'il est souvent possible d'utiliser une tournure neutre (tant pour les titres, que le contenu des exemples) comme forme d'écriture inclusive.

Si une telle tournure reste introuvable, rien n'empêche d'utiliser le point médian (en aucun cas le point).
Encore une fois, je pense (avis personnel s'il en est) que le caractère fondamentalement technique de MDN fait que toute question de genre dans son contenu est hors sujet.

@DavidLibeau je ferme cette *issue* en espérant que cela réponde à ta question.
