### ISSUE TITLE
Forum : icônes des réseaux sociaux avec liens génériques

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#168]
Sur les pages de Geckozone, en pied de page, les icônes de réseaux sociaux ont des liens génériques sous-jacents. Ces icônes n'apparaissent apparemment qu'avec le style de forum proflat.

**Comment by pascalchevrel** [comment]
Avec la migration à phpBB3.3 on retourne sur le thème subsilver, donc ça règle le problème.
