### ISSUE TITLE
Boutons des en-têtes de courriels de Thunderbird

### ISSUE THREAD

**Issue by Christian-V** [mozfr/besogne#170]
Bonjour.
Deux critiques/suggestions concernant la zone d'affichage de l’en-tête des courriels :

    Il manque un bouton ou un autre moyen de basculer simplement entre les en-têtes complets et normaux sans passer par le menu Affichage/En-têtes.

- Ce serait bien agréable pour gagner de la place plus facilement, la consultation de l’en-tête complet étant ponctuelle.

 - Par contre les boutons “Répondre”, “Transférer” et “Indésirable” me paraissent peu utiles puisqu’ils doublonnent ceux de la barre de boutons.
Il vaudrait mieux à mon sens mettre à la place certains des boutons placés actuellement dans “Autres”

**Comment by TheoChevalier** [comment]
Bonjour,

Merci pour les suggestions.
Ce dépôt sert à la coordination de la communauté francophone de Mozilla, qui n’est pas en charge du développement de Thunderbird. Les demandes de modification de Thunderbird peuvent se faire (en anglais) [via Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=Thunderbird ) en suivant [ces recommandations](https://developer.mozilla.org/fr/docs/Recommandations_pour_l%27%C3%A9criture_d%27un_bug)

Je ferme ce ticket, car nous ne sommes pas en mesure de le traiter
