### ISSUE TITLE
Rubriques Nouvel Onglet vides dans Firefox 57 ou 58 - bug

### ISSUE THREAD

**Issue by Christian-V** [mozfr/besogne#171]
Bonjour, je ne sais pas si c'est une bogue d'une variante particulière (Linux ?) de Firefox, si elle est connue ou encore si c'est un pb dû à une extension ou autre cause, mais chez moi, une page de **nouvel onglet** comporte toujours des cadres vides "Sites les plus visités" et "Eléments clés" (toutes les préférences étant cochées).
J'ai déjà posé sans résultat le problème ailleurs :
 https://forums.mozfr.org/viewtopic.php?f=5&t=135738
Je rappelle que je suis sous  Firefox 58 (64b sous Linux Mint 18.2 KDE), et que j'ai seulement les plugin d'origine (H264 et Flash) et les extensions Adblock plus, Print Edit WE, Save Page WE, Free Tabs et Video Downloadhelper (avec le convertisseur "companion" préconisé).
Et le fait de démarrer sans extension ou même de "rafraîchir" Firefox ne change rien.

P-S : Peu habitué à ce site, je n'ai pas bien compris le système d'étiquettes, je mets donc "bug" à toutes fins utiles dans le titre.

**Comment by TheoChevalier** [comment]
Bonjour, même chose que pour Thunderbird ici https://github.com/mozfr/besogne/issues/170, les bugs de Firefox doivent être signalés [via Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox)

Merci !
