### ISSUE TITLE
Traduction de Switch from Chrome to Firefox

### ISSUE THREAD

**Issue by ghost** [mozfr/besogne#173]
hello :)

Je vous propose de traduire ce billet 
https://blog.mozilla.org/firefox/switch-chrome-firefox-just-minutes/
C'est très court, juste une incitation à changer de navigateur en insistant sur la facilité, la rapidité et le peu de risques.

Pad de traduction : 
https://mypads.framapad.org/mypads/?/mypads/group/mozilla-private-ar5c279u/pad/view/switch-from-chrome-to-firefox-056yqy73t

**Comment by ghost** [comment]
ah j'avais oublié le label "traduction" tss

**Comment by ghost** [comment]
J'ai fait un premier jet, qui veut relire/corriger ?
Je peux passer sur le blog par la suite si personne ne s'en occupe.

**Comment by Mozinet-fr** [comment]
relu

**Comment by ghost** [comment]
hop c'est publié, merci Pierre
