### ISSUE TITLE
Traduction extension Facebook contexte

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#177]
Je vous propose de traduire les billets des blogs de Mozilla publiés par Nick Nguyen : [Being Open and Connected on Your Own Terms with our New Facebook Container Add-On](https://blog.mozilla.org/blog/2018/03/27/facebook-container-add-on/) et [Facebook Container Extension: Take control of how you’re being tracked](https://blog.mozilla.org/firefox/facebook-container-extension/) (27 mars).

Pad de traduction : https://mypads.framapad.org/p/facebook-dans-un-contexte-4w2dye7js

**Comment by TheoChevalier** [comment]
Ici aussi du coup, la bonne adresse pour le pad : https://mypads.framapad.org/p/facebook-dans-un-contexte-4w2dye7js

**Comment by Mozinet-fr** [comment]
Publié le 28 mars : [Facebook Container : une extension pour garder le contrôle sur vos données Facebook](https://blog.mozfr.org/post/2018/03/Facebook-Container-extension-garder-controle-vos-donnees-Facebook)
