### ISSUE TITLE
rechercher les DOSSIER des marque-page

### ISSUE THREAD

**Issue by dardaner** [mozfr/besogne#180]
Bonjour,

est il possible dans un prochaine mise a jour de Firefox d'ajouter une fonction qui serait vraiment utile pour chaque utilisateur de Firefox.

Actuellement l'outil recherche des marque-page ne recherche que les marque-page seulement, on ne peut pas rechercher les DOSSIER des marque-page.

Donc est il possible d'ajouter cette fonction :
Avoir la possibilité de rechercher par mot clé les DOSSIER des marque-page et pas seulement les marque-page.

Merci de votre attention

Cordialement ,
utilisateur régulier de Firefox.

**Comment by TheoChevalier** [comment]
Bonjour,

Merci pour les suggestions.
Ce dépôt sert à la coordination de la communauté francophone de Mozilla, qui n’est pas en charge du développement de Firefox. Les demandes de modification de Firefox peuvent se faire (en anglais) [via Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox) en suivant [ces recommandations](https://developer.mozilla.org/fr/docs/Recommandations_pour_l%27%C3%A9criture_d%27un_bug)

Je ferme ce ticket, car nous ne sommes pas en mesure de le traiter
