### ISSUE TITLE
1 coquille

### ISSUE THREAD

**Issue by alexis-michaud** [mozfr/besogne#187]
Sur [cette page](https://github.com/mozfr/besogne/wiki/Common-Voice-fr): 
"Corpus vocaux scientifiques en français sur Ortholang"
C'est Ortolang, pas Ortholang.

**Comment by Mozinet-fr** [comment]
Merci de ta vigilance et du signalement. C'est corrigé.

NB : c'est un wiki, tu peux corriger toi-même.
