### ISSUE TITLE
Mettre à jour les logos de Firefox et de Thunderbird sur mozfr.org

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#188]
Le logo de Firefox n'a pas été mis à jour pour la version Quantum. Depuis aujourd'hui, Thunderbird a aussi un [nouveau logo à la Quantum](https://demo.identihub.co/thunderbird#/).

**Comment by Mozinet-fr** [comment]
lié à #122

**Comment by lhirlimann** [comment]
Bon j'ai regardé les nouveaux logo, Mais y a pas juste une icone en couleur :(  Des idées ?

**Comment by lhirlimann** [comment]
Les logos firefox c'est https://github.com/mozfr/www/pull/132
