### ISSUE TITLE
La machine diplo.mozfr.org ne répond plus

### ISSUE THREAD

**Issue by laurentj** [mozfr/besogne#197]
Pas de ping, d'accés SSH, HTTP, etc. 

Les mailings lists et quelques sites sont impactés. 

- un redémarrage de la machine ne résoud pas le problème
- le monitoring OVH n'était pas activé. Je l'ai réactivé. 
- le monitoring OVH a detecté le problème. Intervention OVH à venir.

@lhirlimann @mgoessen

**Comment by lhirlimann** [comment]
Y a in ticket chez ovh

**Comment by laurentj** [comment]
oui : 

```
[TICKET#5375527264] OVH Monitoring

Notre système de monitoring vient de détecter un défaut sur votre
serveur ks390239.kimsufi.com. Le défaut a été constaté à la date 2018-09-24 10:34:00

Notre équipe de techniciens sur site (opérationnelle 24h/24, 7j/7),
a été informée de ce défaut et va intervenir sur votre machine.

Sachez que d'autres interventions peuvent être en cours actuellement
et qu'il faut compter en moyenne 30 minutes par intervention et par
machine.
Par conséquent, nous ne pouvons pas vous donner plus de précisions
quant à l'heure de début de l'intervention.

Vous recevrez un email dés qu'un technicien prendra en charge votre
serveur. En attendant, vous avez la possibilité de le rebooter à partir
de votre manager.

Logs:
----------------------
PING ks390239.kimsufi.com (188.165.242.92) from 213.186.33.13 : 56(84) bytes of data.
From 213.186.33.13: Destination Host Unreachable
From 213.186.33.13: Destination Host Unreachable
From 213.186.33.13: Destination Host Unreachable

--- 188.165.242.92 ping statistics ---
10 packets transmitted, 0 packets received, +6 errors, 100% packet loss
```

**Comment by lhirlimann** [comment]
Nos services viennent d'intervenir pour bloquer une attaque
entrante sur le serveur ks390239.kimsufi.com et plus
particulièrement sur l'adresse 188.165.242.92.

Cette adresse est maintenant protégée pendant une période
de 1 heure.

Cet état sera maintenu jusqu'au 2018-09-24 12:23:16.

Pour plus d'informations, merci de prendre contact avec
notre service technique.

Elle est pas completement à jour j'ai pas patché depuis début Aout :(

**Comment by mgoessen** [comment]
Ils sont mignons à bloquer les attaques sur une machine qui ne ping/ssh plus.
Je regarde aux alentours de 18h. Je ne peux pas avant. Les mails/ml seront impactés, mais rien ne sera perdu (si la machine revient ...)

**Comment by laurentj** [comment]
OVH a remplacé la carte mère. Les services sont up.

```
Actions entreprises: 
Remplacement de la carte mere.
Mise a jour de l'adresse MAC pour prise en compte du DHCP.
Redemarrage du serveur.

Resultat: 
DHCP OK. Boot OK. Serveur sur 'login'. Ping OK, services demarres.
```


Incident terminé
