### ISSUE TITLE
Relais de campagnes de dons amies 2018

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#198]
Envoyé ce 17 novembre à la [liste communautaire](https://mozfr.org/liste) : [\[com\] Relais de campagnes de dons amies 2018](https://listes.mozfr.org/pipermail/moz-fr/2018-November/009728.html) 

Bonjour à toutes et à tous,

Il y a une série d'organisations amies qui défendent des valeurs 
similaires aux nôtres, auxquelles certains d'entre nous participent 
aussi et avec lesquelles nous nous retrouvons sur les même stands et 
dans les mêmes conférences.

Nous en avons déjà soutenues certaines et, à l'occasion des campagnes de 
dons de fin d'année, nous pouvons renouer nos relations et amplifier 
chacun nos messages.

Depuis plusieurs années, nous avons une bannière de soutien de La 
Quadrature du Net sur mozfr.org[1].

L'année dernière, nous avions eu une discussion sur cette liste à propos 
du relais des campagnes de dons de fins d'année d'organisations amies en 
plus de la fondation Mozilla[2].

Avaient été proposées (sans contredit) :
— La Quadrature du Net
— Tails
— Tor (dont Nos oignons)
— Framasoft
— l'April

Tails[3] et La Quadrature du Net[4] avaient fait l'objet d'un article de 
blog.

En avril, nous avions soutenus Tails, Tor, Let's Encrypt et ToS;DR au 
sein du DuckDuckGo Challenge 2018[5].

Le projet GitHub *Collecte de dons*[6] ouvert l'an dernier peut resservir.

Qu'en pensez-vous ? Qui veut participer ?

[1] https://mozfr.org/
[2] https://listes.mozfr.org/pipermail/moz-fr/2017-November/009553.html
[3] https://blog.mozfr.org/post/2017/11/Tails-a-besoin-de-vous
[4] 
https://blog.mozfr.org/post/2017/12/Aidons-La-Quadrature-du-Net-a-proteger-nos-libertes
[5] https://blog.mozfr.org/post/2018/04/Aidez-les-changer-monde-chaque-jour
[6] https://github.com/mozfr/besogne/projects/2

@+,

-- Pierre alias Mozinet

**Comment by lhirlimann** [comment]
Super  rien a redire

**Comment by chperrot** [comment]
Bonjour,

Je rajouterais bien OpenStreetMap dans la liste surtout que l'antenne française lance un appel aux dons pour renouveler ses serveurs.

[1] https://openstreetmap.assoconnect.com/billetterie/offre/90295-e-renouvellement-de-nos-serveurs
[2] https://twitter.com/OSM_FR/status/1064574027287719938

Amicalement,

Christophe

**Comment by Mozinet-fr** [comment]
Publié sur la liste le 12 déc. à 16h19 : [\[com\] Relais de campagnes de dons amies 2018](https://listes.mozfr.org/pipermail/moz-fr/2018-December/009733.html) :

Bonjour à toutes et à tous,

Donc, jusqu'ici, nous n'avons pas eu le temps d'avancer concrètement sur cette série d'articles. Au vu des quelques réponses et suggestions via divers canaux, nous avons programmé un article par semaine (hormis Mozilla) jusqu'à fin décembre pour :

— La Quadrature du Net
— Tails
— Nos Oignons

Si vous voulez qu'on publie un article sur une autre des associations amies identifiées, faites les recherches et fournissez-moi les informations brutes ou à mettre en avant cette année et je rédigerai l'article. N'hésitez pas à me contacter, même en privé, pour toute question, même mineure.

Merci d'avance,

-- Pierre alias Mozinet
