### ISSUE TITLE
Erreurs 503 récurrentes sur dotclear et phpbb (admin)

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/besogne#199]
On a de fréquentes erreurs 503 sur l'admin du forum et de dotclear. Etant donné qu'on ne semble pas en avoir sur transvision et que côté site public on a bcp de cache statique, je vais supposer que c'est du côté de la BDD que ça merde.

exemple de log pour les forums
[Tue Dec 11 17:32:01.180431 2018] [proxy_fcgi:error] [pid 28540:tid 140533284439808] [client 2a00:8c40:243:224:b1ab:b685:64a:6aa5:52218] AH01067: Failed to read FastCGI header, referer: https://forums.mozfr.org/adm/index.php?i=acp_users&sid=147bee9caea27dd910affa67662c6295&icat=124&mode=overview&u=84814
[Tue Dec 11 17:32:01.180473 2018] [proxy_fcgi:error] [pid 28540:tid 140533284439808] (104)Connection reset by peer: [client 2a00:8c40:243:224:b1ab:b685:64a:6aa5:52218] AH01075: Error dispatching request to : , referer: https://forums.mozfr.org/adm/index.php?i=acp_users&sid=147bee9caea27dd910affa67662c6295&icat=124&mode=overview&u=84814
[Tue Dec 11 17:33:02.484505 2018] [negotiation:error] [pid 28540:tid 140533217298176] [client 157.55.39.130:18680] AH00687: Negotiation: discovered file(s) matching request: /var/www/forums.mozfr.org/feed (None could be negotiated).

**Comment by mgoessen** [comment]
Hello.

Je n'arrive pas bien à cerner l'erreur...

Dans le doute, je viens d'augmenter,
- le max_execution_time de PHP de 30 à 60s (/etc/init.d/php5/fpm/php.ini)
- le request_terminate_timeout à 60 pour PHP-FPM (/etc/init.d/php5/conf.d/01-local.conf)

Le timeout du proxy apache->php (/etc/apache2/conf-enabled/php-fpm.conf) semble ok : d'après https://httpd.apache.org/docs/2.4/fr/mod/mod_proxy.html#proxytimeout elle est déjà à 300

Autre piste: la règle cron qui vide l'opcache php régulièrement (mais je ne pense pas que ce soit ça, elle ne tourne qu'à 2,7,12,17,22,27,32,37,42,47,52,57 et certaines erreurs semblent être à d'autres moments).

Dites moi si les changements faits semblent aider..

**Comment by Mozinet-fr** [comment]
Il devient très difficile de poster sur Dotclear tellement il y a d'erreurs 503.

**Comment by lhirlimann** [comment]
Je viens de mettre le nivau de log a debug dans /etc/php5/fpm/php-fpm.conf (comme il se relance préiodiquement - on verra peut etre plus de choses)

**Comment by lhirlimann** [comment]
mais ça aide en rien. Faudrait sans doute regarder du cote de robots.txt

**Comment by mgoessen** [comment]
Salut !

J'avais augmenté le cache php il y a quelques semaines, pensant résoudre le problème. Visiblement ça l'a empiré.

Je viens de le désactiver completement, ça va dégrader un peu les perfs, mais semble résoudre le problème ... 

Grrr ce cache ...

**Comment by mgoessen** [comment]
Hello,

Avec une dizaine de jours de recul, est ce que vous voyez encore des 503 ? Souvent ?

Je peux laisser le cache désactivé, ou essayer de le tweaké

**Comment by Mozinet-fr** [comment]
Je n'ai plus eu d'erreur 503 dans Dotclear depuis la manipulation.

**Comment by pascalchevrel** [comment]
Pas d'erreur phpbb depuis le changement. Je pense qu'on peut imaginer de remettre opcache en place après la migration à php 7.x seulement.
