### ISSUE TITLE
Mailing list tuppervim - absence d'envoi des e-mails

### ISSUE THREAD

**Issue by maggick** [mozfr/besogne#204]
Il semblerait que les e-mail envoyés à destination de la liste de diffusion tuppervim ne sont pas relayés.
(https://listes.mozfr.org/mailman/listinfo/tuppervim)

En effet, ce problème a été remonté par un de nos contributeur :
https://github.com/tupperVim/tuppervim.github.io/pull/189

Afin de tester le problème, j'ai envoyé un e-mail à la liste depuis mon adresse d'administration et celui-ci n'a pas été relayé.

**Comment by fflorent** [comment]
Merci Maggick.

Si vous pouviez corriger ce problème rapidement pour la communication d'un de nos évènements qui arrivera très bientôt, ça serait très apprécié !

Florent

**Comment by JulioJu** [comment]
Ben ça y'est, ça a l'aire de marcher de nouveau depuis ce matin :-)

**Comment by mgoessen** [comment]
Hop,
Il semble que ça déconne à nouveau. Les graphs ne sont pas beaux. J'essai de corriger dans la journée.

**Comment by mgoessen** [comment]
Devrait être mieux. Merci de rouvrir si ça déconne encore. @lhirlimann regardes les graphs..
