### ISSUE TITLE
Les ouvertures et fermetures d'issues Besogne ne vont plus sur IRC #mozfr

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#209]
Les ouvertures et fermetures d'issues Besogne de notre GitHub n'apparaissent plus sur IRC #mozfr.

**Comment by pascalchevrel** [comment]
Je viens de regarder et en fait GitHub a supprimé ce service : 
https://developer.github.com/v3/guides/replacing-github-services/

Je pense qu'il doit être possible de faire un webhook qui pingue le serveur de mozfr et qui lui enverrait un message sur IRC mais j'avoue que je ne sais pas le faire et là j'ai vraiment pas le temps d'étudier la question :/

**Comment by lhirlimann** [comment]
IRC est mort on peut envisager matrix y a l'air d'avoir des hooks. On change ce bug ou on ferme et on réouvre ?

**Comment by Mozinet-fr** [comment]
Oui, on va avoir plusieurs tâches dans divers domaines pour le passage à Matrix. Je vais créer un projet pour les réunir.
