### ISSUE TITLE
migration site gandi vers une nouvelle Debian

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/besogne#217]
Il faudrait migrer vers une Debian avec PHP7, plusieurs des outils qu'on utilise (notamment notre générateur de sites statiques) ne peuvent plus être mis à jour car notre version de php est trop ancienne (5.6) et ça devient très pénible de mettre à jour le site www.

**Comment by pascalchevrel** [comment]
Debian 9 n'a que 7.0 comme version de PHP, j'aimerais qu'on puisse utilser une version récente de PHP pour pouvoir de nouveau mettre à jour sculpin dont la version minimale de PHP est 7.2.

Le mainteneur des paquets php fournit un dépôt pour mettre à jour son php sur debian ou des vieux ubuntu https://github.com/oerdnj/deb.sury.org

**Comment by lhirlimann** [comment]
Maj prévue en début de semaine prochaine.

**Comment by lhirlimann** [comment]
Donc après avoir regardé ce qu'il y a sur la machine :


1. Passage à strech
2. Maj de MariaDB de 10.1 à la dernière prod ready.
3. Passage a Buster

La suite ensuite.

**Comment by lhirlimann** [comment]
@mgoessen T'as une recommandation pour la DB ?

**Comment by lhirlimann** [comment]
gandi est sous stretch - prochaine étape - pas ce soir , upgrade de mysql
puis passage sous buster.

@pascalchevrel a priori tout fonctionne de ce que j'ai vu - tu peux quand même vérifier phpmydadmin ?

**Comment by pascalchevrel** [comment]
Les sites sont toujours servis avec php 5.6 (ça m'étonnait aussi que rien ne soit pété :) )

**Comment by pascalchevrel** [comment]
On a migré
