### ISSUE TITLE
Matamo (ex Piwik) reconfigurer les sites

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/besogne#219]
Matamo était pété depuis des lustres pour apparemment un problème de configuration (127.0.0.1 vs localhost dans son fichier de config), je suppose suite à sa migration de la machine OVH à la machine Gandi.

C'est réparé, je l'ai mis à jour et j'ai mis à jour le js sur www. Il faudrait mettre à jour ou réinsérer ce js sur tous les sites.

**Comment by Mozinet-fr** [comment]
Pour le blog, le token a changé ?

**Comment by pascalchevrel** [comment]
> Pour le blog, le token a changé ?

non

**Comment by pascalchevrel** [comment]
a priori ça marche pour tous les sites maintenant
