### ISSUE TITLE
Nettoyer le menu du wiki des pages vraiment obsolètes

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#220]
Le menu de wiki sert de liste exhaustive des pages parmi lesquelles beaucoup sont trop obsolètes pour servir à quoi que ce soit sauf à perdre le ou la nouvelle venue.

**Comment by Mozinet-fr** [comment]
Cocher pour désindexer :

Introduction

- [ ]     Accueil
- [ ]     Occasions de contributions idéales pour débuter
- [x]     Idées de contribution
- [ ]     IRC
- [ ]     Parrains Mozilla fr
- [x]     GitHub pour les nuls
- [x]     Questions fréquentes
- [ ]     Qui a les droits ?
- [x]     Projets de Mozilla et apparentés
- [ ]     Lexique

Événements

- [ ]     Conférences
- [x]     Actualités
- [ ]     Mercredi Doc
- [x]     Locasprint
- [x]     Apero petits nouveaux
- [x]     TupperVim
- [x]     Premier Samedi du Libre
- [x]     Réunion mensuelle
- [x]     Webmaker

Traduction / Localisation

- [ ]     Traduction
- [ ]     Guide stylistique pour la traduction
- [ ]     Premiers pas avec Pontoon
- [x]     Traduction de Sumo
- [x]     Firefox & Vous
- [ ]     Étapes d'une traduction d'article
- [ ]     Mise à jour de la traduction des produits Mozilla
- [x]     Localisation avec Bugzilla

Assistance

- [ ]     Assistance
- [ ]     FAQ Assistance de Firefox
- [x]     Contact Répondre aux mails

Communication

- [ ]     Communication
- [ ]     Guide du débutant
- [ ]     Guide pratique du rédacteur
- [ ]     Comment travaille le groupe communication
- [x]     Thunderbird communication

Techno / Code

- [x]     Techno
- [ ]     Contribuer à MDN
- [ ]     Common Voice fr
- [ ]     DeepSpeech fr
- [ ]     Devops
- [x]     TupperVim
- [ ]     GitHub
- [ ]     Jeux web
- [ ]     MozEventBox
- [ ]     MozEventBox Materiel
- [x]     Firebug

Annexes

- [x]     Pads
- [ ]     Tutoriels
- [ ]     Licence

**Comment by Mozinet-fr** [comment]
Les pages obsolètes sont répertoriées sur [cette page du wiki](https://github.com/mozfr/besogne/wiki/Pages-obsol%C3%A8tes).

**Comment by maggick** [comment]
Effectivement ,bien qu'issu de Mozilla, TupperVim n'a plus vraiment de rapport. Et le lien vers le site https://tuppervim.org n'apporte pas grand chose.
