### ISSUE TITLE
Remerciements Gandi

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#223]
Nous avons enfin rédigé (@hellosct1) des tweets de remerciement. Si vous avez d’autres idées d’attaque…

> Nous remercions @gandi_net qui héberge nos sites et qui maintient nos espaces nous permettant de nous consacrer pleinement à @firefox_fr https://www.gandi.net/fr

> Sans @gandi_net, vous ne pourriez pas accéder à nos sites web et services en ligne. Nous les remercions chaleureusement https://www.gandi.net/fr

**Comment by Mozinet-fr** [comment]
Prévoit-on une nouvelle salve à la rentrée ?

**Comment by lhirlimann** [comment]
Oui

**Comment by lhirlimann** [comment]
pour moi c'est bon on a mis une remerciement dans le headre et les tweet sont partis.
