### ISSUE TITLE
Certains destinataires ne recoivent plus de mail

### ISSUE THREAD

**Issue by lhirlimann** [mozfr/besogne#226]
@pascalchevrel : @mgoessen , Usul, on me dit sur les forums que certains ne reçoivent plus les emails de notification de réponse depuis plusieurs jours, est-ce que vous pourriez regarder ce qui se passe sur le serveur côté mail .

Il me semble qu'on est blacklisté chez free : 
Oct 30 07:51:37 gandi postfix/smtp[1013]: C696F10A90: to=<xxxxx@free.fr>, relay=mx1.free.fr[212.27.48.7]:25, delay=336559, delays=336559/0.11/0.21/0, dsn=4.0.0, status=deferred (host mx1.free.fr[212.27.48.7] said: 451 too many errors detected from your IP (95.142.174.97), please visit http://postmaster.free.fr/ (in reply to DATA command))

j'ai trouvé ça par ailleur : 
Oct 30 04:49:25 gandi postfix/smtpd[10179]: warning: TLS library problem: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol:s23_srvr.c:635:

Tous nos certifs pour https sont gérés via letsencrypt : 
root@gandi:/etc/postfix# find / -name "*pem" |grep -v backup |grep -v postfix
/var/lib/letsencrypt/certs/piwik.mozfr.org.pem
/var/lib/letsencrypt/certs/notreinternet.mozfr.org.pem
/var/lib/letsencrypt/certs/mozfr.org.pem
/var/lib/letsencrypt/certs/bugzilla.mozfr.org.pem
/var/lib/letsencrypt/certs/wiki.mozfr.org.pem
/var/lib/letsencrypt/certs/gandi.mozfr.org.pem
/var/lib/letsencrypt/certs/blog.mozfr.org.pem
/var/lib/letsencrypt/certs/transvision-beta.mozfr.org.pem
/var/lib/letsencrypt/certs/planete.mozfr.org.pem
/var/lib/letsencrypt/certs/forums.mozfr.org.pem
/var/lib/letsencrypt/certs/tech.mozfr.org.pem
/var/lib/letsencrypt/certs/transvision.mozfr.org.pem
/var/lib/letsencrypt/certs/nightly.mozfr.org.pem
/var/lib/letsencrypt/certs/firefoxos.mozfr.org.pem
/var/lib/letsencrypt/letsencrypt_intermediate.pem

main.cf contient : 
smtp_tls_cert_file			=	/etc/postfix/ssl/mozfr.org.pem
smtp_tls_CAfile				=	/etc/postfix/ssl/gandi.pem
smtp_tls_key_file			=	/etc/postfix/ssl/mozfr.org.key
smtp_tls_CApath				=	/etc/ssl/certs

et ils datent de 2016/2017 je pense que c'est à cause de ça que Free tique.

solutions : 
* https://upcloud.com/community/tutorials/secure-postfix-using-lets-encrypt/ ?

@mgoessen t'en penses quoi ?

**Comment by lhirlimann** [comment]
le contenu de /var/lib/letsencrypt/Maildir est bizarre aussi.

**Comment by laurentj** [comment]
Je vais utiliser les certif letsencrypt dans main.cf. Il faudra trouver une solution ensuite pour relancer postfix automatiquement à chaque fois que le certificat est regénéré (sachant que je n'avais pas utilisé certbot pour letsencrypt)

**Comment by laurentj** [comment]
- j'ai remplacé les certificats dans /etc/postfix/ssl/ par les certificats générés par letsencrypt. Les anciens ont été renommé en old_* au cas où.
- j'ai modifié /usr/local/bin/letsencrypt_cron.sh pour qu'après chaque execution, il copie le certificat letsencrypt dans /etc/postfix/ssl et redémarre postfix
- j'ai modifié le fichier sudoer de letsencrypt pour qu'il ait le droit de relancer postfix

Pour voir si tout ça a un effet, il faut attendre 24h, temps de blacklistage de notre ip.

**Comment by laurentj** [comment]
Bon, le problème du blacklist, c'est que le compteur de blacklistage est remis à 24h régulièrement. IL y a donc un autre problème ?

**Comment by lhirlimann** [comment]
421 Server busy, too many connections from your IP - hum et si on purgeait la queue pour tous les mail en @free.fr ?

**Comment by lhirlimann** [comment]
root@gandi:/var/log# postsuper -d ALL deferred
postsuper: Deleted: 54 messages

**Comment by lhirlimann** [comment]
OK le user adrien239@free.fr n'existe plus mais reçoit moult notification - @pascalchevrel tu peux configurer le forum pour qiue ce compte n'envoie pas de mail ?

**Comment by lhirlimann** [comment]
ça peut aussi venir de www-data@gandi.mozfr.org

**Comment by pascalchevrel** [comment]
> OK le user [adrien239@free.fr](mailto:adrien239@free.fr) n'existe plus mais reçoit moult notification - @pascalchevrel tu peux configurer le forum pour qiue ce compte n'envoie pas de mail ?

J'ai désactivé ce compte depuis le panneau d'administration, je suppose que ça stoppera les emails mais je suis pas sûr.

**Comment by lhirlimann** [comment]
bon après avoir vidé la queue. nous ne sommes plus listé chez free.
