### ISSUE TITLE
La connexion a échoué sur mozfr.org

### ISSUE THREAD

**Issue by hellosct1** [mozfr/besogne#227]
Bonjour

Le nom de domaine mozfr.org n'est plus accessible

Le message est La connexion a échoué

Le problème touche le domaine mozfr.org et les sous domaines 
comme

mozfr.org/
https://blog.mozfr.org/
www.mozfr.org 
https://mozfr.org/participer 

Merci par avance

Christophe

**Comment by lhirlimann** [comment]
@laurentj  in soucis avec letsencrypt ? Serais dispo début d'aprem pour
regarder

**Comment by pascalchevrel** [comment]
@lhirlimann @mgoessen @laurentj systemctl status apache2.service
```
● apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2)
  Drop-In: /lib/systemd/system/apache2.service.d
           └─forking.conf
   Active: failed (Result: exit-code) since jeu. 2019-10-31 10:18:53 CET; 8s ago
  Process: 11332 ExecStop=/etc/init.d/apache2 stop (code=exited, status=0/SUCCESS)
  Process: 11221 ExecReload=/etc/init.d/apache2 reload (code=exited, status=1/FAILURE)
  Process: 6443 ExecStart=/etc/init.d/apache2 start (code=exited, status=1/FAILURE)

```

**Comment by mgoessen** [comment]
Hello
> <pascalc> [13:09:14] apache2ctl configtest
> <pascalc> [13:09:15] AH00526: Syntax error on line 19 of /etc/apache2/sites-enabled/www.mozfr.org.conf:
> <pascalc> [13:09:17] SSLCertificateKeyFile: file '/var/lib/letsencrypt/private/mozfr.org.key' does not exist or is empty
> <pascalc> [13:09:21] effectivement ce fichier est manquant

Effectivement le fichier était manquant. Je l'ai repris des backups (et l'ai mis dans /root au besoin)

Laurent, le dossier a été modifié hier au moment de ton autre changement. Avais tu supprimé ce fichier ? Si oui c'est pas grave. Si non, ça veut dire qu'il faut qu'on vérifie que les scripts ne refassent pas le coup demain/un jour.

**Comment by mgoessen** [comment]
# ls -al /var/lib/letsencrypt/private/
total 120
drwx--x--- 2 letsencrypt ssl-cert    4096 Oct 30 13:33 .
drwxr-xr-x 7 letsencrypt letsencrypt 4096 Oct 30 13:48 ..

**Comment by lhirlimann** [comment]
ça fonctionne pour moi pour le momement et toi @hellosct1 ?

**Comment by hellosct1** [comment]
bonjour

Merci à tous, c'est bon pour moi
je ferme le ticket
