### ISSUE TITLE
Créer des bridges entre chat.mozilla.org et les groupes Telegram

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#231]
Comme c'était le cas entre l'IRC de Mozilla et les groupes Telegram francophones, il serait bien que la nouvelle solution de Mozilla soit en miroir avec nos groupes.

Références :

- https://github.com/mozfr/besogne/issues/209
- https://github.com/mozfr/besogne/wiki/IRC

**Comment by ioqt00** [comment]
https://matrix.org/bridges
