### ISSUE TITLE
Dotclear : la prochaine version exige PHP 7

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#247]
Le développeur de Dotclear a averti que la [prochaine version majeure exigerait PHP 7](https://open-time.net/post/2020/11/09/Liste-a-cocher). Le tableau de bord de notre instance signale :

> Les prochaines versions de Dotclear ne supporteront par les versions de PHP < 7.0, la votre est actuellement la 5.6.40-0+deb8u4

**Comment by pascalchevrel** [comment]
On a php 7.3 maintenant sur le serveur
