### ISSUE TITLE
Vidéo : montrer comment poser une question dans geckozone

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/besogne#25]
Tous les jours, je dois expliquer à des utilisateurs novices comment poser une question dans les forums pour leurs problèmes d'assistance.

Si j'avais une vidéo à leur envoyer comme lien, ça me ferait gagner du temps.

**Comment by Flore-mozfr** [comment]
Voilà c'est fait : https://www.dropbox.com/s/yvejzwwqebhpvrx/cr%C3%A9ation%20sujet%20forums%20court.mp4?dl=0
Tu n'as plus qu'à la poster sur le compte youtube et fermer cette issue

**Comment by pascalchevrel** [comment]
Publié, merci Flore ! :)
https://www.youtube.com/watch?v=9biwl_eUWec
