### ISSUE TITLE
Accès au Chat Mozilla à partir du chat de Thunderbird

### ISSUE THREAD

**Issue by jrd10** [mozfr/besogne#250]
Bonjour à la communauté francophone de Mozfr,
Merci de ce site.

Je n'arrive pas à me connecter sur le chat Mozilla à partir du chat de Thunderbird (Je suis déjà connecté sur Freenode par exemple).

En anonyme avec le compte `chat.mozilla.org`, j'ai un timeout ! Idem avec mon compte du chat avec le mot de passe de Firefox :).

Quelques recherches : 
- https://support.mozilla.org/fr/kb/messagerie-instantanee-et-tchat
- Et l'issue sur la mise à jour du tuto :).

Note : Pour le nouveau compte, j'ai choisi le network IRC.

Merci de votre retour, amicalement, José

**Comment by benoit-l** [comment]
Bonjour José,

Le serveur IRC de Mozilla a été désactivé il y a environ un an, les discussions se déroulant désormais sur un serveur Matrix : https://github.com/mozfr/besogne/wiki/Matrix

Il n'est pour l'instant pas possible de s'y connecter aisément avec Thunderbird (bien que ce soit [prévu](https://bugzilla.mozilla.org/show_bug.cgi?id=1572636)), il faut utiliser l'interface web sur https://chat.mozilla.org/ ; ou un autre client compatible Matrix.

**Comment by jrd10** [comment]
Merci du retour.
