### ISSUE TITLE
Ajustements menu du haut

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/besogne#252]
* Je vais enlever le lien vers le wiki car c'est une ressource interne plus qu'externe.
* Je vais renommer "forums" par "forums et assistance", 99% de l'activité du forum c'est l'assistance et c'est aussi comme ça qu'on le nomme en bas de page.

**Comment by lhirlimann** [comment]
>"forums et assistance"

+1000

> Je vais enlever le lien vers le wiki

Y a encore de l'activité sur le wiki ? on a encore le besoin d'un wiki ? ou pourrait ptet le miger en resource statiques ?

**Comment by pascalchevrel** [comment]
Le wiki ne coûte rien à maintenir vu que c'est sur notre dépôt github
