### ISSUE TITLE
Créer une bibliothèque de présentation en HTML5

### ISSUE THREAD

**Issue by Flore-mozfr** [mozfr/besogne#26]
Ce serait idéal d'avoir une bibliothèque de présentations sur différents thèmes (par exemple vie privée, sécurité, mozilla, mozfr, Firefox Desktop, Firefox OS...). Où chacun pourrait puiser pour préparer rapidement une conf pour un événement.
Le format HTML5 serait idéal pour ça pour plusieurs raisons : 
1. ça met en avant les possibilité du HTML5, de Firefox
2. c'est interopérable : mac, windows, linux on s'en fout ce qui compte, c'est Firefox pour passer la présentation
3. on peut avoir un design commun pour toutes les présentations mozfr, il suffit d'avoir un designer qui édite la présentation modèle et tout le monde reprend le css.

On peut partir des [présentations mozilla (en HTML5)](https://www.mozilla.org/en-US/styleguide/communications/presentations/) et modifier le design :

**Comment by SphinxKnight** [comment]
Il y a https://github.com/Mte90/Mozilla-Presentation-Boilerplate/ qui a qqc de sympa :)

**Comment by lhirlimann** [comment]
tu t'y colles ?

**Comment by SphinxKnight** [comment]
Wokay

**Comment by SphinxKnight** [comment]
https://sphinxknight.github.io/Presentation_MozFR cay bieng ? 
@lhirlimann @Flore-mozfr 
Si OK je pousse sur un dépôt mozfr et éventuellement je crée une démo avec une pres qu'on a par ailleurs.

**Comment by SphinxKnight** [comment]
J'ai utilisé le logo, le fond du site mozfr.org et un peu de son CSS. (à tenir compte si on modifie le site…)

**Comment by SphinxKnight** [comment]
Bon allez, je ferme, j'ai mis ça là https://github.com/mozfr/Presentation_MozFR avec un pti README.md qui va bieng avec
