### ISSUE TITLE
Création d'un site de téléchargement pour Firefox Nightly

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/besogne#27]
Il est impossible d'obtenir de Mozilla qu'ils fassent une version localisée de nightly.mozilla.org donc pratiquement impossible d'avoir des utilisateur sous Nightly en français, hors ils sont les meilleurs bêta testeurs et ont le profil de contibuteurs.

Donc on va faire notre propre site de téléchargement pour Nightly. https://nightly.mozfr.org

**Comment by pascalchevrel** [comment]
Il y a une source des versions de Firefox Desktop,ici:
https://svn.mozilla.org/libs/product-details/json/firefox_versions.json
A priori, la rajouter et incrémenter la valeur de AURORA de 1 devrait tout en passant de a2 à a1 devrait suffir, un truc du genre : 

``` php
function getNightlyNumber()
{
    $source = 'https://svn.mozilla.org/libs/product-details/json/firefox_versions.json';
    $nightly = explode('.', json_decode(file_get_contents($source), true)['FIREFOX_AURORA']);
    $nightly[0]++;
    $nightly[1] = str_replace('2', '1', $nightly[1]);

    return implode('.', $nightly);
}

print getNightlyNumber();
```

**Comment by pascalchevrel** [comment]
ébauche de site ici http://dev.pascalc.net/
code temporaire: https://github.com/pascalchevrel/nightly

**Comment by Mozinet-fr** [comment]
Et Nightly pour Android ?

**Comment by TheoChevalier** [comment]
L’APK sur https://nightly.mozilla.org/ est directement en français.

**Comment by Mozinet-fr** [comment]
Il serait peut-être bien de le préciser. La preuve que ce n'est pas évident.

**Comment by pascalchevrel** [comment]
c'est un site pour destop pour l'instant, pour mobile on verra après.

**Comment by pascalchevrel** [comment]
d'après Sylvestre, le futur site qui aura les json sera là :
https://product-details.mozilla.or g/
j'essaye de voir avec lui si ça aurait plus de sens de faire Release+3 que Aurora+1

**Comment by dattaz** [comment]
on ne pourrait pas juste reprendre les sources de nightly.mozilla.org et localiser nous même la page et la mettre sur mozfr ?

**Comment by TheoChevalier** [comment]
Non, on ne peut pas reprendre ce design, on doit en créer un autre.

**Comment by TheoChevalier** [comment]
Liste de ce dont on aurait besoin (au moins pour une première version)
- Page d’accueil :
  - [x] Liens de téléchargement. Sous quelle forme ? En liste, comme actuellement ? Utiliser des listes déroulantes pour choisir le système puis l’architecture puis proposer le bon lien ? Boutons radio pour faire apparaître le bon lien ?
- À mettre quelque part :
  - [x]  Lien vers les forums geckozone (forums dédiés aux versions de dev)
  - [x]  Expliquer comment signaler un bug (logiciel ou de loca)
  - [x]  Un canal IRC à conseiller pour discuter des problèmes ? (un en anglais, un en français ?)
  - [ ]  Lien(s) vers MozFR ?
  - [ ]  Lien vers mozRegression ? (même si ça ne fonctionne pas avec les versions localisées)
  - [ ]  Lien vers liste des bugs ouverts récemment pour Firefox (pour trouver facilement les doublons)
  - [x]  Un onglet par plateforme
- Sur chaque page spécifique à une plateforme : 
  - [x] un/deux bouton(s) de téléchargement (32/64 bits)
  - [ ]  un tutoriel avec des captures pour installer plusieurs profils avec une version stable. Mentionner Sync pour synchroniser les données, avec un petit lien vers SUMO.
  - [x] Mentionner quelque part que ces versions se mettent à jour toutes seules, comme la version stable ? (Y compris sous Linux, beaucoup vont, à tort, chercher un PPA)
- Une page à part « À propos » :
  - [x] Description des builds nightly 
  - [x] Pourquoi les utiliser, pourquoi c’est important pour Mozilla
  - [ ] Avertissements (bugs, plantages, pertes de données, en indiquant les probabilités).  Par contre on laissera probablement l’avertissement sur l’envoi de données télémétriques sur la page de téléchargement.
- Propositions de lignes directrices pour le design :
  - [x] Référence soit à la nuit (thème sombre), soit au développement (sans tomber dans le thème de Firefox Dev Edition), soit au thème du chantier, (autres propositions dans cet esprit bienvenues)
  - [x] Utiliser le logo Nightly à un endroit ou un autre https://www.mozilla.org/en-US/styleguide/identity/firefox/channels/
  - [x] Garder une page d’accueil relativement épurée, bien mettre en évidence le/les bouton(s) de téléchargement

De façon générale, se démarquer du design du site Mozilla, mais il faut que l’utilisateur comprenne rapidement que le site propose de télécharger les versions Nightly officielles de Mozilla, pas des compilations faites par la communauté (juste le mentionner peut suffire).

N’hésitez pas à ajouter des idées si vous voyez d’autres choses, et à proposer des idées pour le design. Je vais probablement commencer à bosser sur un truc ces jours-ci, en créant une branche séparée. Comme ça, des gens pourront m’aider s’ils le souhaitent :)

**Comment by TheoChevalier** [comment]
Ce que j’ai en tête pour l’instant pour la page d’accueil. Sans les couleurs c’est pas facile à imaginer, mais globalement faut regarder la structure surtout.
Les listes déroulantes seraient personnalisées pour être affichées en couleur, et de façon plus visible.

Le faux globe en bas serait bien plus fin que sur le dessin, mon idée c’est juste de suggérer un globe.

Des avis ?

![img_20151223_120530](https://cloud.githubusercontent.com/assets/1294206/11975495/e7f0947a-a96e-11e5-8e49-bba436876e30.jpg)

**Comment by TheoChevalier** [comment]
Version en cours :
Le code est sur cette branche : https://github.com/TheoChevalier/nightly/tree/design

![capture d ecran 2015-12-24 a 01 35 28](https://cloud.githubusercontent.com/assets/1294206/11987408/faa984d0-a9de-11e5-9c7c-c1237082128c.png)

**Comment by pascalchevrel** [comment]
classe :+1: 
Je pense que des icônes windows/mac/linux seraient bien. Idéalement, on pourrait mettre en avant l'OS avec un lien vers l'ancre et mettre une capture écran différente qui correspondrait à l'OS

**Comment by pascalchevrel** [comment]
J'ai transféré la propriété de mon dépôt nightly à mozfr :
https://github.com/mozfr/nightly

Tu peux faire des PRs

**Comment by TheoChevalier** [comment]
On peut fermer ça, https://nightly.mozfr.org
