### ISSUE TITLE
Installation des paquets principaux pour le web

### ISSUE THREAD

**Issue by laurentj** [mozfr/besogne#29]
Paquets à installer sur la nouvelle machine pour un serveur web
- [ ] paquets apache
- [ ] paquets php avec php-fpm plutôt que le module php
- [ ] mysql avec nouveau mot de passe root
- [ ] installer les certificats ssl
- [ ] installer les différents fichiers de config apache à partir de l'ancienne machine (snippets/, conf.d/?) mais ne rien activer...
- [ ] installer awstats

**Comment by pascalchevrel** [comment]
Est-il possible, juste pour Transvision, d'avoir du PHP 7 à plus ou moins court terme? J'ai sur une partie de l'API qui est lente un gain de perf x3 sans rien changer au code, ce qui m'intéresse fortement, avoir un projet en PHP 7 est aussi attractif pour les nouveaux contributeurs.

**Comment by ghost** [comment]
remplacer apache par nginx?
remplacer awstats par piwik?

Pour php7, il serait bon de tester sur une autre machine la compatibilité complète du code actuel de transvision avec php7 ?

**Comment by pascalchevrel** [comment]
on a déjà piwik installé, rien contre nginx mais je pense que c'est un obstacle à la contribution pour les non pro comme moi (j'ai pas réussi à le configurer en local alors qu'apache c'est un clic)

**Comment by pascalchevrel** [comment]
Transvison fonctionne parfaitement sous PHP7 vu que c'est ce que j'utilise depuis les premières alphas et que j'ai même rapporté des bugs à la core team PHP grâce à ça

**Comment by ghost** [comment]
Ok , mais quid des builds sur debian ? ça a l'air d'être dans sid (et pas la stable, on dirait la rc4 ?!)…

**Comment by pascalchevrel** [comment]
PHP 7 est dispo sur dotbeb mais je sais que geb sera contre.Malheureusement mon expérience de Debian est que toute nouvelle version ne sera supportée officiellement que dans des années,  donc si on installe pas de paquet externe la seule autre solution c'est de le compiler.

**Comment by mgoessen** [comment]
Salut.

Je suis en effet assez contre dotdeb, pour avoir eu des machines qui n'ont jamais passé les mises à jour, et simplement car je trust plus l'équipe de sécurité debian que celle de dotdeb.

Je n'ai pas régardé dans le détail ce qui se fait coté debian, mais il semble que les paquets soient arrivés dans sid. Si le besoin est réel, nous ne seront pas les seuls à en avoir besoin, et ils seront sans doute rapidement disponible dans testing et dans les backports. Le fait qu'ils soient arrivés dans sid me le laisse facilement croire. Attendons quelques semaines et je pense qu'on aura la réponse :)

**Comment by mgoessen** [comment]
J'ai également oublié de répondre pour nginx.
- Ce changement ne nous apporterait rien de plus que quelques % de performances vis à vis d'apache mpm-worker/event
- On utilise énormement les htaccess etc qui ne sont pas supportés par nginx. Cela me semble donc délicat

**Comment by mgoessen** [comment]
Fait.
