### ISSUE TITLE
Vidéo : thème léger dans Firefox

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/besogne#3]
Faire une vidéo présentant l'installation d'un thème léger dans Firefox.

**Comment by lhirlimann** [comment]
La v1 est dispo à http://dl.free.fr/rlFnma4AS @Mozinet-fr @pascalchevrel @Flore-mozfr  vos avis svp.

**Comment by Mozinet-fr** [comment]
Pourquoi tout ce MSN et Bing au départ ?

Tu pourrais montrer comme on les gère dans apparence (supprimer, revenir au thème par défaut…) en parlant de la barre grise qui se rajoute après une installation.

**Comment by lhirlimann** [comment]
Parceque quand t'installe firefox sur du windows ça importe IE qui a ces default là :)

Ok je le note. Je referrais demain ou la semaine prochaine sans doute.

**Comment by lhirlimann** [comment]
v2 http://dl.free.fr/s0Z03l5R1

**Comment by Mozinet-fr** [comment]
VLC : Impossible de reconnaître le format du média d'entrée:
Le format de « file:///F:/Pictures/capture/actu%20Mozilla/Desktop01.17.2017-14.32.27.01.mp4 » n'a pu être détecté. Vérifiez les messages pour plus de détails.
Impossible de reconnaître le format du média d'entrée:
Le format de « file:///F:/Pictures/capture/actu%20Mozilla/Desktop01.17.2017-14.32.27.01.mp4 » n'a pu être détecté. Vérifiez les messages pour plus de détails.

Firefox dit qu'il est corrompu.

**Comment by Mozinet-fr** [comment]
Sur la nouvelle vidéo http://dl.free.fr/stzcXGY7u sur #mozfr :
12:15:13 - Mozinet : […] j'ai pu la lire cette fois
12:15:13 - Mozinet : Problème de MSN en page d'accueil
12:15:36 - Mozinet : Grosse pub et Marion Maréchal Le Pen en gros plan
12:15:59 - Mozinet : tu ne parles que des thèmes légers pas des thèmes en général
12:16:40 - Mozinet : Le discours sur Nightly est perturbateur pour un tutoriel grand public
12:17:05 - Mozinet : Nightly n'a pas les mêmes fonctions dans ce cas que le stable
12:17:31 - Mozinet : Le thèmes compacts sont des nouveautés dans Nightly (53)
12:17:58 - Mozinet : ce ne sont pas des thèmes téléchargés
12:18:27 - Mozinet : tu ne parle pas directement du retour au thème par défaut
12:18:50 - Mozinet : j'aimais bien quand tu partais du catalogue
12:19:20 - Mozinet : tu pourrais aussi montrer l'ouverture du gestionnaire de modules complémentaires
13:06:38 - Usul : j'ai un desktop d'uitlisateur normal sur cette machine j'aime bien le garder
13:25:54 - Mozinet : Usul: juste un petit changement d'onglet pour la home page de Firefox suffirait. Tu reviens ensuite

**Comment by Mozinet-fr** [comment]
Dans la page de personnalisation de Firefox, il y a aussi un menu Thèmes avec des thèmes proposés.

**Comment by lhirlimann** [comment]
Hop la v3 http://dl.free.fr/nddl430KO
@pascalchevrel @Mozinet-fr  ça vous va.

**Comment by pascalchevrel** [comment]
https://www.youtube.com/watch?v=-7XiyK8qTX0

**Comment by Mozinet-fr** [comment]
Vidéo intégrée dans l'[article du mois Mots-zilla du jour sur AMO](https://blog.mozfr.org/post/2017/06/AMO-mois-Mots-zilla)

et publiée comme contenu principal sur nos réseaux : voir [la carte Trello](https://trello.com/c/eAKR2HLZ).
