### ISSUE TITLE
Installer & configurer le backup

### ISSUE THREAD

**Issue by laurentj** [mozfr/besogne#31]
Installer l'outil de backup, le configurer, et configurer la cible des backups

**Comment by ghost** [comment]
Vu sur l'irc, il semblerait qu'une backup complète du système est journalière et non incrémentale.
Je vous conseille de basculer sur:
1 backup complète du système / semaine -> + garder 1 mensuelle si place dispo
et de basculer sur 1 backup incrémentale / jour (sera plus rapide)

**Comment by mgoessen** [comment]
Pour la cible:
- on peut utiliser un autre disque sur gandi
- si on a une machine secondaire, on peut la mettre dessus.

Pour le logiciel, je propose backupninja. Il y a un bug avec rsync qu'il faut le patcher (je l'ai déjà fait) mais:
- Il marche bien
- Il a de vrais logs, de vrais rapports par mail et de vrais warning au cas où.
- le dev (intrigeri) est dispo sur #frenchmoz

**Comment by mgoessen** [comment]
Il permet de plus d'exprimer facilement (plus que notre outil actuel) des politiques évoluées telles que celles que proposent fabien.

**Comment by mgoessen** [comment]
Fait. Pour l'instant installé avec backup journalier et une semaine de rétention. Je pense que cela sera pas mal de garder un snapshot mensuel ou autre, donc je laisse le bug ouvert pour l'instant.

**Comment by lhirlimann** [comment]
pas la peine de garder ouvert indéfiniment.
