### ISSUE TITLE
Migrer www.mozfr.org

### ISSUE THREAD

**Issue by laurentj** [mozfr/besogne#34]
- [ ] vérifier ce qu'il y a à migrer exactement pour ce site et completer cette checklist
- [ ] ancien serveur : Fermer le site ou le mettre en lecture seule, de manière à ne plus empecher les modifs de fichiers ou de la base de donnée
- [ ] ancien serveur : backup de la base pour archives...
- [ ] new serveur : creation des users systèmes nécessaires au site
- [ ] new serveur : installation des fichiers du sites, et reglages des droits
- [ ] new serveur : creation et activation vhost apache
- [ ] configuration awstats pour le site, et importer les statistiques awstats
- [ ] tester le site avec la nouvelle ip déclarée dans un /etc/hosts local
- [ ] dns : changer l'ip avec celle du nouveau serveur

**Comment by pascalchevrel** [comment]
On est passés à un site statique la semaine dernière avec sculpin, l'installation est triviale, juste déplacer le dossier et faire pointer le vhost sur le dossier output_prod
