### ISSUE TITLE
Migrer wiki.mozfr.org

### ISSUE THREAD

**Issue by laurentj** [mozfr/besogne#36]
- [ ] vérifier ce qu'il y a à migrer exactement pour ce site et completer cette checklist
- [ ] ancien serveur : Fermer le site ou le mettre en lecture seule, de manière à ne plus empecher les modifs de fichiers ou de la base de donnée
- [ ] ancien serveur : backup de la base
- [ ] new serveur : creation de la base et de ses utilisateurs
- [ ] new serveur : import du backup de la base dans mysql
- [ ] new serveur : creation des users systèmes nécessaires au site
- [ ] new serveur : installation des fichiers du sites, et reglages des droits
- [ ] new serveur : creation et activation vhost apache
- [ ] configuration awstats pour le site, et importer les statistiques awstats
- [ ] tester le site avec la nouvelle ip déclarée dans un /etc/hosts local
- [ ] dns : changer l'ip avec celle du nouveau serveur

**Comment by pascalchevrel** [comment]
on a tout sur github et on y redirige
