### ISSUE TITLE
Migrer les sites xulfr.org

### ISSUE THREAD

**Issue by laurentj** [mozfr/besogne#39]
Pour chaque site xulfr :
- [x] vérifier ce qu'il y a à migrer exactement pour ce site et completer cette checklist
- [x] ancien serveur : Fermer le site ou le mettre en lecture seule, de manière à ne plus empecher les modifs de fichiers ou de la base de donnée
- [x] ancien serveur : backup de la base
- [x] new serveur : creation de la base et de ses utilisateurs
- [x] new serveur : import du backup de la base dans mysql
- [x] new serveur : creation des users systèmes nécessaires au site
- [x] new serveur : installation des fichiers du sites, et reglages des droits
- [x] new serveur : creation et activation vhost apache
- [x] tester le site avec la nouvelle ip déclarée dans un /etc/hosts local
- [x] dns : changer l'ip avec celle du nouveau serveur

**Comment by lhirlimann** [comment]
Y a encore des trucs dynamique ?

**Comment by laurentj** [comment]
c'est du php avec base mysql. Donc oui, tout est dynamique. Mais je m'en occuperais.

**Comment by pascalchevrel** [comment]
@laurentj tu peux t'en occuper s'il te plaît ?

**Comment by laurentj** [comment]
Ok je vais m'y mettre

**Comment by laurentj** [comment]
Sur un serveur PHP récent (5.6), les applications de xulfr sont complément cassées, en particulier le dotclear utilisé qui est très très vieux. Et je ne parle pas du forum (motorisé par Phorum qui n'est plus maintenu depuis des années). À cela il faut ajouter tout le contenu qui est obsolète depuis longtemps.

Je n'ai pas le temps ni l'envie de réparer tout ça. Je vais donc fermer xulfr.org, et heberger une page bouchon ailleurs que sur le serveur mozfr.

**Comment by laurentj** [comment]
Finalement, je vais quand même migrer le site. J'ai commencé à remplacer dotclear par des scripts maison. Je vais faire pareil pour les forums. Mais pour les deux, ça ne sera que de la lecture seule.

**Comment by laurentj** [comment]
Le nettoyage du site et la suppression/remplacement du code legacy est terminé. Reste maintenant à le migrer.

**Comment by laurentj** [comment]
Migration effectuée !
