### ISSUE TITLE
passer mozfr.org en ssl

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/besogne#4]
Une fois la refonte de www avec sculpin terminée, il faudrait que l'on redirige tout notre traffic de http vers https.

Aujourd'hui on ne le fait pas parce qu'on syndique du contenu externe en page d'accueil et qu'en ssl ça génère des erreurs mixed-content)

**Comment by Flaburgan** [comment]
Let's encrypt is coming. Bientôt on aura du SSL partout :)

Pour éviter le mixed content dans diaspora\* on a mis en place Camo, pour proxifier le contenu non chiffré qui vient de l'extérieur.

**Comment by pascalchevrel** [comment]
on a déjà un certificat wildcard pour mozfr depuis cet été, d'ailleurs tu peux visiter le site en https, mais pour http://mozfr.org on a laissé http justement pour ne pas avoir à proxifier le contenu externe. Maintenant qu'on aura plus de contenu externe vu qu'on ne syndiquera plus de blogs en page d'acceuil, on peut rediriger http vers https

**Comment by pascalchevrel** [comment]
fait
