### ISSUE TITLE
Migrer mozilla.pt

### ISSUE THREAD

**Issue by laurentj** [mozfr/besogne#41]
- [ ] vérifier ce qu'il y a à migrer exactement pour ce site et completer cette checklist
- [ ] ancien serveur : Fermer le site ou le mettre en lecture seule, de manière à ne plus empecher les modifs de fichiers ou de la base de donnée
- [ ] ancien serveur : backup de la base
- [ ] new serveur : creation de la base et de ses utilisateurs
- [ ] new serveur : import du backup de la base dans mysql
- [ ] new serveur : creation des users systèmes nécessaires au site
- [ ] new serveur : installation des fichiers du sites, et reglages des droits
- [ ] new serveur : creation et activation vhost apache
- [ ] configuration awstats pour le site, et importer les statistiques awstats
- [ ] tester le site avec la nouvelle ip déclarée dans un /etc/hosts local
- [ ] dns : changer l'ip avec celle du nouveau serveur

**Comment by lhirlimann** [comment]
J'ai filé un compte pour la migration wordpress a jxs :)

**Comment by lhirlimann** [comment]
email de relance envoyé.

**Comment by lhirlimann** [comment]
Pas de réponse , @pascalchevrel on fait la migration nous même ?

**Comment by lhirlimann** [comment]
Je propose qu'on ferme tou simplement le site - dernière maj debut 2018. bcp d'activité en 2016 , un billet ou deux en 2017. c'est archivé correctement il me semble https://web.archive.org/web/*/http://mozilla.pt/ . Vous en pensez quoi ?

**Comment by lhirlimann** [comment]
Puisque personne ne répond mozilla.pt va disparaitre.

**Comment by lhirlimann** [comment]
rm du symlink + restart de apache.
