### ISSUE TITLE
Migrer transvision

### ISSUE THREAD

**Issue by laurentj** [mozfr/besogne#42]
- [ ] vérifier ce qu'il y a à migrer exactement pour ce site et completer cette checklist
- [ ] ancien serveur : Fermer le site ou le mettre en lecture seule, de manière à ne plus empecher les modifs de fichiers ou de la base de donnée
- [ ] ancien serveur : backup de la base
- [ ] new serveur : creation de la base et de ses utilisateurs
- [ ] new serveur : import du backup de la base dans mysql
- [ ] new serveur : creation des users systèmes nécessaires au site
- [ ] new serveur : installation des fichiers du sites, et reglages des droits
- [ ] new serveur : creation et activation vhost apache
- [ ] configuration awstats pour le site, et importer les statistiques awstats
- [ ] tester le site avec la nouvelle ip déclarée dans un /etc/hosts local
- [ ] dns : changer l'ip avec celle du nouveau serveur

**Comment by pascalchevrel** [comment]
Il n'y a pas de base dans Transvision. L'installation peut se faire from scratch avec un simple git clone, puis renseigner dans le fichier app/config/config.ini divers paramètres (chemins des dépôts, infos piwik...) et ensuite juste lancer le script setup.sh. ça prend en gros 2h et tout est fonctionnel.

**Comment by pascalchevrel** [comment]
Pas assez de place sur /var/ pour réupérer les dépôts

Checking out the following repo:
/var/cache/transvision/hg//BETA_EN-US/mozilla-beta/
destination directory: mozilla-beta
requesting all changes
adding changesets
adding manifests
adding file changes
transaction abort!
failed to truncate 00changelog.i
rollback failed - please run hg recover
abort: No space left on device: '/var/cache/transvision/hg/BETA_EN-US/mozilla-beta/.hg/store/.phaseroots-u4cBTi'

**Comment by pascalchevrel** [comment]
df -h /var/
Sys. de fichiers Taille Utilisé Dispo Uti% Monté sur
/dev/root          9,8G    5,5G  3,9G  59% /

La partition est trop petite pour récupérer les dépôts mozilla, il faut au moins 30Go juste pour Transvision.

**Comment by pascalchevrel** [comment]
fait
