### ISSUE TITLE
Annonce de disponibilité de Firefox 43

### ISSUE THREAD

**Issue by TheoChevalier** [mozfr/besogne#43]
Ce serait bien de traduire ce soir la courte annonce de disponibilité de Firefox 43 qui vient de paraître :
https://blog.mozilla.org/blog/2015/12/15/firefox-gives-you-more-control-over-your-data-in-private-browsing/

J’ai ouvert un pad ici  https://public.etherpad-mozilla.org/p/firefox-43-fr

**Comment by TheoChevalier** [comment]
Capture fr pour la traduction 
![capture du 2015-12-15 19-14-57](https://cloud.githubusercontent.com/assets/1294206/11819488/61b1cfd2-a360-11e5-99a9-04299f2742de.png)

**Comment by Mozinet-fr** [comment]
La section presse fr n'est pas sur le coup ?

**Comment by TheoChevalier** [comment]
Le traducteur habituel ne nous a rien donné à relire, donc il ne semblerait pas.

**Comment by Mozinet-fr** [comment]
https://blog.mozilla.org/press-fr/2015/12/16/firefox-vous-offre-plus-de-controle-sur-vos-donnees-dans-le-mode-navigation-privee/

**Comment by TheoChevalier** [comment]
Arf… Bon bah ce coup-ci ils ont décidé de pas nous faire relire… 
Je ferme le ticket du coup, désolé.

**Comment by Mozinet-fr** [comment]
Et pourtant il y avait des erreurs comme « Mozilla a récemment dévoilé la protection contre le postage » et c'est régulier. Les traductions montrent régulièrement (lire presque toujours) qu'ils ne sont pas du monde de Mozilla.

**Comment by TheoChevalier** [comment]
Tu prêches un convaincu ;)
