### ISSUE TITLE
Traduire et relayer l'appel aux dons de la fondation mozilla

### ISSUE THREAD

**Issue by Flore-mozfr** [mozfr/besogne#44]
Le texte a été envoyé par email aux mozilliens, mais il serait bien de le relayer sur notre blog et nos réseaux sociaux.

---

 Hello there,

This is it. This is the time of year we ask you to help Mozilla protect this precious public resource—the open Web.

It’s up to us. Starting with our friends and family, we want more people to gain control of their online lives. We want everyone to know how to be safe and feel safe online—and even build something to add to the open nature of the Web. After all, that’s how we got Firefox. That’s how we keep the Web strong.

Mozilla has big plans to grow this movement, but we can’t do it without you. That’s why we need your support.

Your previous gift helped us to preserve net neutrality and educate more users about protecting their privacy—we can’t thank you enough. We need your help to keep the momentum going. That’s why we’re asking you to make your year-end gift right now, before our campaign ends on December 31st.

We’re in a historic moment for the Web. Whistleblowers like Edward Snowden, data breaches by major retailers and credit card companies, and surveillance overreach have all heightened awareness. People are seeking answers, and Mozilla can help.

We have big plans. We want to mobilize more people in more countries to get involved and to help us take a stand when the open Web is in trouble. This is how we’ll preserve the open nature of the Internet for generations to come.

We’ve been able to grow this movement thanks to the past support of people like you. A gift to our year-end campaign helps us continue building this movement of Web citizens around the world—will you give right now?.

Momentum is on our side. We are growing the world’s largest movement to protect the open Web—and it’s a good thing, because threats to the Web are growing, too. That is why we need many more people to join us.

Your support helps Mozilla change the world for the better by ensuring everyone can participate in a Web that is open and free.

Thank you for all you do for Mozilla,

Andrea

Andrea Wood
Director, Digital Advocacy + Fundraising

P.S.  Don’t forget: The deadline to give is December 31st -- we appreciate every donation. (FYI—if you give right now, you won’t receive any more fundraising emails this year. Don’t wait!) 

---

pad pour la traduction : https://public.etherpad-mozilla.org/p/mofo-appel-aux-dons

**Comment by Mozinet-fr** [comment]
Ça en est où ?

**Comment by Flore-mozfr** [comment]
Bonjour à tous,

Voilà, nous y sommes. C'est l'époque de l'année où nous vous demandons d'aider Mozilla à protéger cette ressource publique et précieuse qu'est le Web ouvert.

C'est à nous de le faire. Pour nos amis et notre famille, nous voulons qu'un maximum de gens prennent le contrôle de leur vie en ligne. Nous voulons que chacun sache comment se protéger et puisse se sentir en sécurité en ligne – et peut-être même construise quelque chose et apporte un peu au Web ouvert. Après tout, c'est comme ça que s'est fait Firefox. C'est comme ça que nous garderons le Web solide.
Mozilla a de grands projets pour amplifier ce mouvement, mais nous ne pouvons pas y arriver sans vous. C'est pourquoi [nous avons besoin de votre aide](https://donate.mozilla.org/fr/).
Vos précédents dons nous ont aidés à préserver la neutralité du Net et à apprendre à plus d'utilisateurs à protéger leur vie privée, nous ne pouvons vous en remercier assez. Nous avons besoin de votre aide pour continuer dans notre élan. C'est pourquoi nous vous demandons de faire votre don de fin d'année maintenant, avant la fin de notre campagne le 31 décembre.
Nous sommes à un moment historique pour le Web. Les lanceurs d'alerte comme Edward Snowden, les fuites de données chez les grands commerçants, les compagnies de carte de crédit ainsi qu'une surveillance exagérée ont participé à une prise de conscience aigüe. Les gens cherchent des réponses et Mozilla peut aider.
Nous avons de grands projets. Nous voulons mobiliser plus de personnes dans plus de pays pour les impliquer et nous aider à défendre le Web quand il est en danger. C'est ainsi que nous préserverons la nature ouverte d'Internet pour les générations à venir.
Nous avons pu faire grandir ce mouvement grâce au soutien passé de gens comme vous. Un don pour notre campagne de fin d'année nous aide à continuer de construire ce mouvement de citoyens du Web autour du monde, le ferez-vous maintenant ?

Cet élan est de notre côté. Nous faisons grandir le plus grand mouvement pour protéger un Web ouvert, et c'est une bonne chose, car les menaces sur le Web grandissent aussi. C'est pourquoi nous avons besoin de beaucoup plus de gens de notre côté.

Votre aide permet à Mozilla de changer le monde pour le mieux, en s'assurant que tout le monde peut participer au Web ouvert et gratuit.

Merci de tout ce que vous faites pour Mozilla,
Andrea

Andrea Wood
Directrice des projets Digital Advocacy et Fundraising

P.-S. N'oubliez pas : [la date butoir pour donner est le 31 décembre](https://donate.mozilla.org/fr/) – Chaque don compte.

**Comment by Flore-mozfr** [comment]
Il faut se dépêcher, il reste 10 jours. Merci de relire et de faire vos commentaires rapidement.
Je le publie ce soir.

**Comment by TheoChevalier** [comment]
On peut retirer les : après le P.-S., mais c’est clairement pas bloquant. Tu peux y aller, Flore

**Comment by TheoChevalier** [comment]
Une seconde lettre sera publiée mercredi, en passant

**Comment by Flore-mozfr** [comment]
On poste celle-ci maintenant et l'autre jeudi ?
Ce serait dommage de faire l'impasse sur celle-là alors qu'on l'a traduite

**Comment by TheoChevalier** [comment]
Oui oui on la poste sans plus attendre, justement

**Comment by Flore-mozfr** [comment]
Voilà j'ai créé le billet sur le blog.
Titre : Appel aux dons de la fondation mozilla
Catégorie : générale
Mots-clés : mozilla
Des choses à modifier / ajouter ?

**Comment by Flore-mozfr** [comment]
Publié : https://blog.mozfr.org/post/2015/12/Appel-aux-dons-de-la-fondation-mozilla
