### ISSUE TITLE
Relayer l'appel à libération de Bassel Khartabil, Mozillien Syrien condamné à mort

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#45]
Billet de Mitchell Baker évoquant ses souvenirs avec lui : A call for the release of Bassel Khartabil https://blog.lizardwrangler.com/2015/12/16/a-call-for-the-release-of-bassel-khartabil/

et long article du Guardian : Bassel Khartabil: fears for man who brought open internet to the Arab world http://www.theguardian.com/technology/2015/dec/11/bassel-khartabil-fears-for-man-who-brought-open-internet-to-the-arab-world

Il y a eu un article de Thierry Noisette sur ZDNet il y a quelques temps.

**Comment by lhirlimann** [comment]
ça vaut encore le cout ? sinon on ferme.

**Comment by Mozinet-fr** [comment]
L'appel est trop ancien.
