### ISSUE TITLE
Mettre un lien vers mozfr depuis la chaine youtube

### ISSUE THREAD

**Issue by lhirlimann** [mozfr/besogne#46]
https://www.youtube.com/channel/UCyieisb28vyXaltYRFsHDaQ/about est vide se serait bien dy mettre un lien :)

**Comment by pascalchevrel** [comment]
Fait, mais il y a un bug d'affichage dans Firefox :/ (dans Chrome c'est bon), le texte est sur une seule ligne et sort du cadre, il n'y a pas de passage à la ligne.

J'ouvrirai un bug Tech Evang plus tard…
