### ISSUE TITLE
Traduction des deux billets hacks sur les Service Workers

### ISSUE THREAD

**Issue by SphinxKnight** [mozfr/besogne#49]
Traduction de : 
- Beyond Offline
  - [article original](https://hacks.mozilla.org/2015/12/beyond-offline/)
  - [pad](https://bimestriel.framapad.org/p/tech-mozfr-beyond-offline)
- Offline Recipes
  - [article original](https://hacks.mozilla.org/2015/11/offline-service-workers/)
  - [pad](https://bimestriel.framapad.org/p/tech-mozfr-offline-recipes)

[Mail envoyé sur moz-fr](http://mozfr.org/pipermail/moz-fr/2015-December/008412.html)

**Comment by SphinxKnight** [comment]
- https://tech.mozfr.org/post/2015/12/26/Recettes-hors-connexion-pour-les-service-workers
- https://tech.mozfr.org/post/2015/12/26/Hors-ligne-et-plus-encore

Voilà :)

**Comment by TheoChevalier** [comment]
Salut, j’arrive après la bataille, mais j’ai trouvé quelques coquilles :)

Recettes hors connexion :
 livre de recette > recettes 
un autre scénario plutot simple > plutôt
installés par les les sites 
chargement de chaque fichier listés > listé

Hors ligne et plus encore :
les scénarios suivant > suivants
Vous vous rappellez > rappelez
demander aux composant > composants
en faisant de multiple requêtes > multiples

**Comment by SphinxKnight** [comment]
Corrigé, merci :)
