### ISSUE TITLE
Coquille dans notre script de rotation des logs

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/besogne#5]
Tous les jours, je reçois ce message d'erreur d'un CRON:

```
Subject: Cron <root@diplo> test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
Date: Mon, 30 Nov 2015 13:25:05 +0100

/etc/cron.daily/logrotate:
Process blog.frenchmozilla.org
Process blog.mozfr.org
Process bugzilla.frenchmozilla.org
Process builds.firefoxos.mozfr.org
Process firefoxos.mozfr.org
Process fortunes.frenchmozilla.org
Process forum.mozfr.org
Process irclog2.frenchmozilla.org
Process irclog.frenchmozilla.org
Process notreinternet.mozfr.org
Process planet.mozfr.org
Process tech.mozfr.org
Process transvision.mozfr.org
Process wiki.mozfr.org
Process www.frenchmozilla.org
Process www.mozfr.org
Process www.mozilla.pt
Process www.womoz.org
Process www.xulfr.org
Process awstats
logrotate_script: 3: logrotate_script: cannot create /deb/null: Directory nonexistent
```

/deb/null devrait être /dev/null

**Comment by lhirlimann** [comment]
root@diplo:/etc/logrotate.d# grep -r deb .
./apache2:      /usr/local/sbin/awstats_mounthchanged.sh > /deb/null
./rsyslog:/var/log/debug
./mysql-server:     # If this fails, check debian.conf! 
./mysql-server:     MYADMIN="/usr/bin/mysqladmin --defaults-file=/etc/mysql/debian.cnf"
./mysql-server:       # Really no mysqld or rather a missing debian-sys-maint user?

**Comment by lhirlimann** [comment]
root@diplo:/etc/logrotate.d# grep -r deb .
./rsyslog:/var/log/debug
./mysql-server:     # If this fails, check debian.conf! 
./mysql-server:     MYADMIN="/usr/bin/mysqladmin --defaults-file=/etc/mysql/debian.cnf"
./mysql-server:       # Really no mysqld or rather a missing debian-sys-maint user?
