### ISSUE TITLE
Afficher l'user agent dans les messages du forum Geckozone

### ISSUE THREAD

**Issue by Patclash** [mozfr/besogne#51]

**Comment by Patclash** [comment]
ça devient vraiment urgent , vu le nombre de soucis sans savoir sur quel système

**Comment by pascalchevrel** [comment]
c'est fait:
https://forums.mozfr.org/viewtopic.php?f=4&t=128932#p817571
patch à inverser et réappliquer avant chaque mise à jour attaché à ce message

[UA3.1.8.txt](https://github.com/mozfr/besogne/files/189560/UA3.1.8.txt)
