### ISSUE TITLE
Modifier les financements de Mozilla sur Wikipedia

### ISSUE THREAD

**Issue by leonarf** [mozfr/besogne#52]
Sur la page https://fr.wikipedia.org/wiki/Mozilla_Foundation, il est dit que Mozilla est financée à 85% par Google ce qui n'est plus vrai. La page anglaise a un paragraphe détaillant le sujet du financement.
Il serait bien de mettre a jour la version française.

**Comment by leonarf** [comment]
Pour ajouter des détails, on peut s'aider des informations disponible via le lien https://www.mozilla.org/en-US/foundation/annualreport/2014/faq/

**Comment by SphinxKnight** [comment]
attention à https://en.wikipedia.org/wiki/Wikipedia:Conflict_of_interest

**Comment by leonarf** [comment]
Je suis resté factuel, et donc j'ai laisser que Mozilla était financé jusqu'à 90% par Google de 2004 à 2014. Mais j'ai ajouté des détails concernant le changement de partenariat avec les moteurs de recherche intervenu en 2015. J'ai aussi ajouté des détails concernant le financement de Mozilla lors de sa création. Vous pouvez lire dans https://fr.wikipedia.org/wiki/Mozilla_Foundation#Histoire
J'ai aussi modifié la page anglaise : https://en.wikipedia.org/wiki/Mozilla_Foundation#Financing

Je clos l'issue, mais vous pouvez la réouvrir si vous trouvez des choses à redire :-)
