### ISSUE TITLE
Sur @mozilla_fr les billets du blog sont poussés automatiquement

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#53]
Sur le compte Twitter @mozilla_fr les billets du blog général sont tweetés deux fois automatiquement. Une nouvelle apparue récemment avec le titre du billet, ses premiers mots (ce qui n'apporte rien, bien au contraire) et l'URL raccourcie par bit.ly, et l'ancienne qui apparaît avec retard (4 heures de plus) avec la balise [Blog MozFR] avant le titre et l'URL raccourcie avec is.gd.

Je ne sais pas si ces raccourcisseurs d'URL sont obligatoires avec l'API, mais sur Twitter ils sont depuis longtemps plus nécessaires, Twitter le faisant lui-même.

Comme c'est le compte de MozFr, si on garde l'idée de la balise, [Blog] suffirait.

**Comment by Mozinet-fr** [comment]
Les billets n'y sont plus poussés automatiquement qu'une fois (titre + début de l'article + URL). Avec un travail de communication et donc de rédaction de messages spécifiques pour chaque article et chaque réseau social, cette publication automatique est contre-productive. Il convient AMA de la supprimer aussi.

**Comment by TheoChevalier** [comment]
J’ai révoqué l’accès de twitterfeed sur le compte Twitter (j’imagine qu’il servait uniquement à ça)
