### ISSUE TITLE
Mettre à jour le tutoriel Bugzilla

### ISSUE THREAD

**Issue by TheoChevalier** [mozfr/besogne#54]
On redirige les nouveaux contributeurs vers https://tech.mozfr.org/post/2013/04/23/Rapporter-un-bogue-sur-Bugzilla pour apprendre à rapporter un bug. Bien que ce soit une traduction, on devrait mettre à jour le billet pour préciser qu’il faut ajouter le mot-clé [mozfr-community] dans le champ whiteboard.

**Comment by lhirlimann** [comment]
Hum aussi y a quelques videos en Anglais se serait bien de fournir les sous-titre en français.

**Comment by SphinxKnight** [comment]
J'ai mis à jour l'article avec une note en début et en ajoutant un texte sur l'image visée.
Pour les vidéos je n'en ai pas dans l'article mais de façon générale, je suis d'accord.
@TheoChevalier à toi de voir si ça suffit pour fermer l'issue.

**Comment by TheoChevalier** [comment]
Merci, c'est parfait
