### ISSUE TITLE
Compression gzip pas activée sur le nouveau serveur

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/besogne#55]
On a noté des problèmes de perfs sur Transvision avec flod et une cause pourrait être que le contenu n'est pas gzippé;
http://checkgzipcompression.com/?url=https%3A%2F%2Ftransvision.mozfr.org%2F

Notre serveur ovh envoie les pages en gzip :
http://checkgzipcompression.com/?url=https%3A%2F%2Fnightly.mozfr.org%2F

Je pense que c'est ce qui cause un effet de clignotement du menu sur transvision sur les pages donnant beaucoup de résultat, parcequ'on doit attendre un gros document avant de pouvoir manipuler le DOM de la page.

**Comment by pascalchevrel** [comment]
fait

**Comment by ghost** [comment]
quelles extensions de fichiers sont concernées par la compression gzip ?
