### ISSUE TITLE
Firefox + Vous [janvier 2016]

### ISSUE THREAD

**Issue by ghost** [mozfr/besogne#56]
La traduction de la  lettre d'informations de Firefox du mois de janvier est ouverte à tous.
Merci d'avance. le pad de brouillon collaboratif est ici, comme d'habitude
https://public.etherpad-mozilla.org/p/FFetV

**Comment by pl6025** [comment]
Voici le calendrier pour la localisation de cette lettre :
Jan. 4: Copy to localizer teams
Jan. 18: Localization due
Jan. 19 to 22: Proofs go out
Jan. 26: Newsletter launches

Voici le suivi des dernières lettres envoyées
December’s newsletter:
Sent: 291,538 (HTML) + 43,888 (TEXT) = 335,426
Open Rate (HTML only): 25.5 %
Click Rate (HTML only):  4.3%

Fundraising email:
Sent: 292,589 (HTML) + 43,056 (TEXT) = 335,645
Open Rate (HTML only): 23.2 %
Click Rate (HTML only):  1.4%

**Comment by ghost** [comment]
la lettre mensuelle de janvier est distribuée par mail et publiée ici 
https://blog.mozfr.org/post/2016/01/Mozilla-Firefox-Vous-janvier-2016-Newsletter-francophone

**MERCI** à tous les contributeurs !

**Comment by ghost** [comment]
publiée
