### ISSUE TITLE
Mettre à jour l’URL du compte Diaspora sur le mozfr.org

### ISSUE THREAD

**Issue by TheoChevalier** [mozfr/besogne#58]
Il suffit juste de changer https://free-beer.ch/u/mozfr par https://diaspora-fr.org/people/c5937eaddec02679 sur le dépôt https://github.com/mozfr/www

**Comment by ghost** [comment]
Tu peux fermer ce ticket @TheoChevalier

**Comment by TheoChevalier** [comment]
Merci ! :)

**Comment by Flaburgan** [comment]
Nope nope nope... Free-beer est down et visiblement pour toujours, il faut donc ouvrir un nouveau compte mozfr pourquoi pas sur framasphere.org. Il ne sert à rien de faire un lien depuis un autre pod sur un compte qui ne peut plus être utiliser.

**Comment by ghost** [comment]
@Flaburgan mais euh il vient justement de mettre un nouveau lien vers https://diaspora-fr.org/people/c5937eaddec02679. Mais d'accord avec toi , je voterai plutôt pour l'ouverture d'un compte sur framasphere.org qui est le pod diaspora francophone le plus important en termes d'utilisateurs.

**Comment by Flaburgan** [comment]
@goofy-bz le lien vers diaspora-fr est simplement l'ancien compte vu depuis diaspora-fr. Le lien aurait pu par exemple être celui depuis framasphere : https://framasphere.org/people/c5937eaddec02679 Ca ne change rien au problème : le serveur free-beer.ch est down depuis des semaines et on arrive pas à joindre l'administrateur, donc il faudrait ouvrir un nouveau compte (par exemple sur framasphere) et mettre ce lien là.
