### ISSUE TITLE
Traduire : Start 2016 Message To Foxfooders - From Ari Jaaksi

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#59]
Je vous propose de traduire ce message en français : Start 2016 Message To Foxfooders - From Ari Jaaksi - Firefox OS Participation - Mozilla Discourse https://discourse.mozilla-community.org/t/start-2016-message-to-foxfooders-from-ari-jaaksi/6420

J'ai créé un pad https://mypads.framapad.org/p/start-2016-message-to-foxfooders-jaaksi-tc3tm70n

Ce n'est pas très long, mais je n'aurais pas le temps de m'y mettre avant ce soir. Si vous avez un peu de temps, n'hésitez pas.

Discussion sur la liste du groupe comm pour Firefox OS http://mozfr.org/pipermail/firefoxos-mozfr/2016-January/001350.html

**Comment by ghost** [comment]
J'ai fini un premier jet, que les connaisseurs de Firefox OS améliorent tout ça :)

**Comment by Mozinet-fr** [comment]
Merci Goofy !

La traduction est incluse dans : https://firefoxos.mozfr.org/post/2016/01/Foxfooders-votre-participation-sera-essentielle
