### ISSUE TITLE
Traduire le billet sur les awards par mozilla

### ISSUE THREAD

**Issue by Flore-mozfr** [mozfr/besogne#6]
Il y a ce billet qui serait intéressant à traduire :

https://blog.mozilla.org/blog/2015/12/10/mozilla-open-source-support-first-awards-made/
Le pad est disponible : https://public.etherpad-mozilla.org/p/FR-Mozilla-open-source-First-Awards

**Comment by ghost** [comment]
Salut. J'ai contribué.
A priori tout est traduit. A relire si possible.

**Comment by SphinxKnight** [comment]
j'ai ajouté quelques bafouilles

**Comment by Flore-mozfr** [comment]
Nous avons le plaisir d'annoncer la première série de récompenses attribuées par le programme de soutien de Mozilla à l'open source, dans la catégorie « Technologies fondatrices », c'est-à-dire tous les projets utilisés par Mozilla ou dont nous dépendons. Nous remercions vivement le [comité MOSS](https://wiki.mozilla.org/MOSS#Selection_Committee) pour son aide très appréciable dans la phase d'évaluation et de récompenses.
Les sept premiers lauréats sont : 

[Buildbot](http://buildbot.net/) : 15 000 $
Buildbot est un système de construction et d'intégration continue qui a été extrêmement précieux pour Mozilla au cours des dernières années. 
Leur prix sera utilisé pour enlever le terme «esclave» de toute la documentation, des API et des tests, et aussi pour apporter des améliorations sur le fonctionnement de Buildbot dans le cloud Amazon EC2.

[CodeMirror](http://codemirror.net/) : 20 000 $
CodeMirror est un puissant éditeur de code source intégré avec les technologies Web, utilisé dans les outils de développement de Firefox et dans Mozilla Thimble. 
Leur prix sera utilisé à la fois pour améliorer le support des langues qui s'écrivent de droite à gauche et celui de l'encodages de scripts complexes.

[Discourse](http://www.discourse.org/) : 25 000 $
Discourse est un logiciel de forum en ligne utilisé par de nombreuses communautés Mozilla. 
Leur prix sera utilisé afin que les courriels deviennent un moyen d'interaction de premier ordre au sein de Discourse, ce qui leur permettra de remplacer et d'améliorer leurs listes de diffusion.

[Read The Docs](https://readthedocs.org/) : 48 000 $
Read The Docs est un site web permettant de créer et d'héberger de la documentation, utilisé par de nombreux projets web de Mozilla. 
Leur prix sera utilisé pour développer une fonctionnalité de génération de documentation à partir du code source, sans avoir besoin de l'installer. Cela simplifiera la construction de la documentation pour les projets complexes.

[Mercurial](https://www.mercurial-scm.org/) : 75 000 $ 
Mercurial est un système de gestion de versions de code source décentralisé massivement utilisé par Mozilla pour ses dépôts les plus importants comme mozilla-central. 
Leur prix sera utilisé pour améliorer la fonctionnalité « blame » (permettant d'afficher qui est responsable du dernier changement d'une ligne de code précise) ainsi  que l'interface web à travers laquelle on consulte un dépôt.

[Django](https://www.djangoproject.com/) : 150 000 $
Django is a popular server-side Web development framework, used in many Mozilla websites. 
Their award will be used to make Django suitable to be a back end for Web apps which use WebSockets.
Django est un framework populaire de développement web côté serveur utilisé par de nombreux  sites web de Mozilla.
Leur prix sera utilisé pour que Django puisse être un backend pour les applications web utilisant WebSockets.

[Bro](https://www.bro.org/) : 200 000 $
Bro est un logiciel de surveillance réseau, qui est au cœur du système de détection d'intrusion réseau de Mozilla.
Leur prix permettra de construire le « Comprehensive Bro Archive Network », un dépôt public de modules et de plugins pour Bro.

MOSS est un programme continu, doté d'un budget initial d'un million de dollars. Les récompenses ci-dessus ont attribué plus de la moitié de ce budget (503 000 $) et la [soumission de projets est toujours ouverte](https://docs.google.com/a/mozilla.com/forms/d/1Pa5IsuhT6vMUfg0HUXxr7SzrSwq5fpiZfZIJVPxN1Mc/viewform) au sein du programme de soutien « Technologies fondatrices ». Demain, nous continuerons à chercher à soutenir davantage les [excellents projets que Mozilla utilise ou sur lesquels il s'appuie](https://wiki.mozilla.org/MOSS/Projects_in_use_by_Mozilla). Merci à tous, nous ne pourrions pas le faire sans vous.

**Comment by Flore-mozfr** [comment]
Voilà la traduction faite sur le pad, prête à être publiée sur le blog
Archivée ici parce que les pads, c'est pas fiable sur le long terme

**Comment by Flore-mozfr** [comment]
Billet publié: https://blog.mozfr.org/post/2015/12/Mozilla-Open-Source-Support-%3A-la-premiere-serie-de-recompenses-attribuees
