### ISSUE TITLE
Traduction du billet sur la stratégie 2016 de Mozilla

### ISSUE THREAD

**Issue by TheoChevalier** [mozfr/besogne#60]
On a reçu une demande de Lucy Harris pour traduire le billet suivant sur la stratégie 2016 de Mozilla :

https://blog.mozilla.org/community/2016/01/06/mozillas-strategic-narrative-for-2016-and-beyond

En cette période de manque de clarté, c’est probablement une bonne idée :) La traduction sera publiée sur le blog officiel.
Si on arrive à traduire/relire d’ici vendredi, ça serait pas mal, même si le plus tôt est le mieux évidemment ;)

Ça se passe sur Google Docs, pas besoin de se connecter pour traduire (si vous n’avez pas de compte) :
https://docs.google.com/document/d/1O1ODsPZgt-3SJrh6Fj22pyWGQphgfCW-yFVjzy0Fbio/edit?usp=sharing

Merci d’avance ! N’hésitez pas à participer même si vous n’avez pas trop l’habitude, c’est l’occasion de commencer et de progresser :)

Message sur la liste de discussion : http://mozfr.org/pipermail/moz-fr/2016-January/008457.html

**Comment by TheoChevalier** [comment]
Merci à tous ceux qui ont participé, le billet est en ligne : https://blog.mozfr.org/post/2016/01/Plan-strategique-de-Mozilla-pour-2016-et-au-dela

(Si jamais vous voyez des erreurs, je peux toujours corriger)

**Comment by leonarf** [comment]
2 remarques en lisant le billet sur blog : 
"Mais si vous demandez à cinq Mozilliens différents ce qu’est au juste cette mission, vous obtiendrez sept réponses différentes." : ça ne devrait pas être soit 5 soit 7, mais pas un mixe si? ça me parait bizarre même si c'est dans le billet en VO peut-être que c'est une expression Anglaise non?

Un moment on écrit "la mission que s’est fixée Mozilla", et autre part "Mozilla ne peut rien faire seul". Mozilla est féminin en premier puis masculin en 2ème non?

**Comment by TheoChevalier** [comment]
Pour le premier point, je ne pense pas que ce soit une expression mais dans le doute j’ai harmonisé. Vu qu’il a pas mal d’erreurs dans le billet VO, c’en est probablement une de plus ;)

Concernant la seconde remarque, fixée s’accorde avec mission et pas Mozilla, car le COD est placé avant.

**Comment by benoit-l** [comment]
Bah c'est juste une blague classique, pas spécifiquement anglaise (demandez à x personnes, vous aurez x+1 opinions). 

Par exemple en français ou en espagnol : http://www.citation-celebre.com/citations/9554 ou http://www.proz.com/kudoz/spanish_to_french/linguistics/1232788-tres_espa%C3%B1oles_cuatro_opiniones.html

Je trouve dommage de l'enlever mais vous faites ce que vous voulez :-)

**Comment by TheoChevalier** [comment]
Ah, j’avais pas pris ça comme un trait d’humour en fait :) Merci Benoit, je l’ai remis

**Comment by Mozinet-fr** [comment]
J'ai changé le premier paragraphe pour enlever l'URL apparente vers le blog et la remplacer par du texte et un lien vers l'article en anglais :

> _Ce billet est une traduction réalisée par la communauté francophone. Le billet original provient du blog [Mozilla about:community](https://blog.mozilla.org/community/2016/01/06/mozillas-strategic-narrative-for-2016-and-beyond/)._
