### ISSUE TITLE
Créer un blog Dotclear firefoxmobile

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#61]
Suite au Message du groupe comm sur son avenir sur la liste générale http://mozfr.org/pipermail/moz-fr/2016-January/008458.html le groupe comm demande la création d'une nouvelle instance de Dotclear « firefoxmobile » pour la communication sur les projets Firefox pour Android et Firefox pour iOS, et les efforts de Mozilla en mobilité. Le blog firefoxos.mozfr.org restant focalisé sur l'OS mobile de Mozilla.

Christophe/Hello pourra attribuer des rôles aux personnes engagées.

**Comment by MatonAnthony** [comment]
Est-ce vraiment nécessaire ? Est-ce réellement pertinent d'avoir un énième blog qui traite des mêmes sujets vagues et à la pertinence toute relative du blog firefoxos (https://firefoxos.mozfr.org/)

Je n'ai pas de décision à prendre hein, je ne donne qu'un avis.
