### ISSUE TITLE
Rediger un texte pour gandi

### ISSUE THREAD

**Issue by mgoessen** [mozfr/besogne#62]
Il faudrait rédiger un texte de quelques lignes si on veut apparaitre sur https://www.gandi.net/soutient/
200-500 mots plus un logo

**Comment by TheoChevalier** [comment]
Je propose cette petite description, largement inspirée d’un passage de la page d’accueil (301 caractères) :

> MozFR est la communauté de bénévoles Mozilla francophones. Elle a un spectre d’activités très large, allant de la traduction des logiciels et sites web de Mozilla au développement d’applications en passant par l’assistance aux utilisateurs et le militantisme dans le domaine de la politique internet.

Le logo (celui de la page d’accueil, en retirant la marge dans le png)
![mozfr](https://cloud.githubusercontent.com/assets/1294206/12349494/6527d4b8-bb70-11e5-88f4-16b6a7942fab.png)

**Comment by Mozinet-fr** [comment]
Détail : si c'est Mozilla francophone, mieux vaudrait éviter le « FR » qui est le code du pays. « Fr » qui n'est pas standard irait très bien. Pourrait-on parler aussi de la promotion des logiciels et projets de Mozilla ?

**Comment by TheoChevalier** [comment]
Propose ta version ? ;)

**Comment by Mozinet-fr** [comment]
MozFr est la communauté de bénévoles Mozilla francophones. Comme Mozilla, elle a un spectre d’activités très large. La communauté aide à la traduction, la promotion, l'assistance aux utilisateurs des produits et services de Mozilla. Elle participe aussi aux actions de la fondation dans l'éducation et le militantisme politique. Tous les Mozilliens francophones ne sont pas développeurs. Ils viennent d'horizons très divers. Rejoignez-les.

439 caractères.

**Comment by TheoChevalier** [comment]
Quelques remarques : on préfère en général parler de logiciels plutôt que de produits, et militantisme politique me semble moins clair, car pas de mention d’internet.
Et pour pinailler, il faudra harmoniser les types d’apostrophes.

À part ça, ça me va

**Comment by Mozinet-fr** [comment]
MozFr est la communauté de bénévoles Mozilla francophones. Comme Mozilla, elle a un spectre d’activités très large. La communauté aide à la traduction, la promotion, l’assistance aux utilisateurs des logiciels et services de Mozilla. Elle participe aussi aux actions de la fondation dans l’éducation et le militantisme dans le domaine de la politique internet. Tous les Mozilliens francophones ne sont pas développeurs. Ils viennent d’horizons très divers. Rejoignez-les.

471 caractères

**Comment by TheoChevalier** [comment]
Merci, c’est parfait de mon côté

**Comment by pascalchevrel** [comment]
Je rajouterais un point d'exclamation à la fin pour ajouter du dynamisme et inciter les gens à nous rejoindre.

**Comment by mgoessen** [comment]
Merci pour le boulot de rédaction. J'ai envoyé le texte. Il devrait apparaître sous peu sur  https://www.gandi.net/soutient/

[Je ferme donc le bug]

**Comment by Mozinet-fr** [comment]
Des nouvelles ?

**Comment by mgoessen** [comment]
Pas encore. Ils nous pingerons au moment de le mettre en ligne je pense. La page ne semble pas avoir été mise à jour.

**Comment by Mozinet-fr** [comment]
Non, je l'ai monitorée : aucun changement depuis l'envoi.
