### ISSUE TITLE
Rediger une annonce de migration du serveur

### ISSUE THREAD

**Issue by mgoessen** [mozfr/besogne#63]
Il faudrait rediger une annonce pour parler de la migration du serveur et la publier sur blog + liste. 

Je peux m'y coller en partie.

**Comment by lhirlimann** [comment]
@Mozinet-fr l'idée et de dire que mozfr est sponsorisé par gandi. que la machine est chez eux et que nous les en remercions.

**Comment by Mozinet-fr** [comment]
[Gandi](https://www.gandi.net/ "Nom de domaine et hébergement cloud – Gandi.net"), le bureau d’enregistrement de noms de domaine et hébergeur web français, soutient [un certain nombre d’organisations](https://www.gandi.net/soutient/ "Nom de domaine et hébergement cloud – Gandi soutient les projets alternatifs – Gandi.net") du domaine du Libre et de la défense des libertés en ligne comme l’_Electronic Frontier Foundation_, _Creative Commons_, Ubuntu, Gnome, VideoLAN, Dotclear ou _Let's Encrypt_. À ce titre, Gandi sponsorise MozFr, et le serveur sur lequel tourne la majeure partie des activités en ligne de la communauté est hébergé par cette société.


La communauté Mozilla francophone remercie vraiment Gandi pour son soutien et [son « supplément d’âme »](https://www.gandi.net/qui-est-gandi/ "Nom de domaine et hébergement cloud - Qui est Gandi ? - Gandi.net").

**Comment by lhirlimann** [comment]
@mgoessen et @pascalchevrel cette annonce me va très bien. Vos avis, s'il est positif, je propose qu'on publie sur le blog sans retard.

**Comment by mgoessen** [comment]
Merci. Si vous voulez bien, je voudrais écrire un truc plus long. Je m'y colle pendant les vacances de noel

**Comment by Mozinet-fr** [comment]
OK, je l'ai inscrit au calendrier des publications pour le 26 (la date sera ajustée alors) https://trello.com/c/tjVrVzvR

**Comment by Mozinet-fr** [comment]
@mgoessen tu en es où ?

**Comment by mgoessen** [comment]
Salut.

Je n'ai pas encore pris le temps d'avancer dessus. Je vous tiens au courant quand c'est fait. On peut essayer de prévoir ça pour fin janvier / courant fevrier. Mais je souhaitais également avoir avancé sur les migrations *avant* de communiquer dessus.

À bientôt,

**Comment by Mozinet-fr** [comment]
OK, j'ai repoussé à fin janvier dans le planning

**Comment by Mozinet-fr** [comment]
@mgoessen une avancée ?

**Comment by lhirlimann** [comment]
On 11/02/2017 19:25, Mozinet wrote:
>
> @mgoessen <https://github.com/mgoessen> une avancée ?
>
on attend d'avoir finit de migrer pour dire merci
>

**Comment by Mozinet-fr** [comment]
@lhirlimann une idée de la date ?

**Comment by lhirlimann** [comment]
Il me semble qu'on a remercier gandi l'année dernière. pas la peine de garder ce ticket ouvert.
