### ISSUE TITLE
Créer un profil pour www.mozfr.org sur l'instance Piwik

### ISSUE THREAD

**Issue by TheoChevalier** [mozfr/besogne#64]
On va avoir besoin de suivre le nombre de visites sur une URL du site www.mozfr.org depuis un snippet Firefox Nightly, il semblerait que Piwik ne soit pas activé pour ce site.
Et il semblerait que je ne puisse pas créer de nouveau site sur l'instace Piwik :)

**Comment by MatonAnthony** [comment]
Hello,

L'instance avait été déployé pour le groupe de comm'.
Du coup j'ai les accès admins et t'ait mis les droits ;)

**Comment by TheoChevalier** [comment]
Merci @MatonAnthony , j'ai pu configurer tout ça comme il faut :+1:
