### ISSUE TITLE
Les forums ont affiché une erreur 503 pendant quelques minutes

### ISSUE THREAD

**Issue by TheoChevalier** [mozfr/besogne#66]
Il semblerait que ce ne soit pas critique, vu que les forums sont de retour, mais on devrait regarder les graphes et logs entre 22h40 et 22h45. 
Durant cette période, j'ai testé la page d'accueil, elle s'affichait toujours.

Hum, mise à jour, maintenant les forums ont affiché :

[forums.txt](https://github.com/mozfr/besogne/files/102560/forums.txt)

**Comment by pascalchevrel** [comment]
Le forums sont fonctionnels mais il y a une grosse charge sur le serveur liée au backups (commandes du, cp, gzip, rsync, rm) qui tournent depuis super longtemps ainsi que munin-graph.

Par exemple là ça fait 30mn que je vois le process rm prendre 30% de CPU, je suis pas sûr que ce soit normal qu'un rm prenne autant de temps. Je serais curieux de savoir quel volume de données on backup.

**Comment by pascalchevrel** [comment]
Process rm qui prend un temps infini : 

26.8  6157 root     rm /srv/mozfr01-backups/backups/3x.rsync/srv/mozfr01-data/mozfr01-data.0/transvision/ /srv/mozfr01-backups/backups/3x.rsync/srv/mozfr01-data/mozfr01-data.1/transvision/ /srv/mozfr01-backups/backups/3x.rsync/srv/mozfr01-data/mozfr01-data.2/transvision/ /srv/mozfr01-backups/backups/3x.rsync/srv/mozfr01-data/mozfr01-data.3/transvision/ /srv/mozfr01-backups/backups/3x.rsync/srv/mozfr01-data/mozfr01-data.4/transvision/ /srv/mozfr01-backups/backups/3x.rsync/srv/mozfr01-data/mozfr01-data.5/transvision/ /srv/mozfr01-backups/backups/3x.rsync/srv/mozfr01-data/mozfr01-data.6/transvision/ -rf

Est-ce que c'est un process qui efface les backups de toute la semaine de Transvision ? (vu que ça va de 0 à 6, ça fait pile 7 jours). À ma connaissance on archive pas transvision-data, je ne sais pas ce que recouvre exactement le dossier transvision, mais si c'est juste l'appli derrière transvision.mozilla.org, il faudrait peut être exclure le dossier Transvision/cache qui est potentiellement très volumineux. Ainsi que transvision/web/data.tar.gz qui est généré automatiquement par l'appli et n'a pas besoin d'être sauvegardé.

**Comment by pascalchevrel** [comment]
@mozfr/admin-sys ping

**Comment by pascalchevrel** [comment]
Pour transvision donc dans le backup on peut exclure :

```
transvision/cache/*.cache (~1Go /jour)
transvision/web/data.tar.gz (200Mo)
transvision/download/*.tmx (300Mo)
```

Ce sont des données générées par l'appli qui n'ont aucune valeur comme archive.
Transvision avec ces données fait ~1,6go, sans ces données il fait 100Mo

**Comment by mgoessen** [comment]
Pour le 503 c'est de ma faute. J'ai changé quelques trucs. J'aurais du attendre une heure ou deux de plus.
Pour transvision également, on backupait par erreur les données de transivision, je l'ai exclu, et ai rm les centaines de milier de fichiers en trop :)
