### ISSUE TITLE
Redirection permanente pour firefoxosblog.mozfr.org

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#68]
Serait-il possible d'avoir une redirection permanente pour [firefoxosblog.mozfr.org](https://firefoxosblog.mozfr.org/) vers [firefoxos.mozfr.org](https://firefoxos.mozfr.org/) ? Il me semble que c'était une adresse de test pour le blog WP envisagé un temps. Elle contient actuellement le contenu de la page d'accueil sous cette adresse. Cela gêne le référencement, car cette adresse apparaît en bonne place dans les moteurs, possiblement avant les pages maintenues.

**Comment by lhirlimann** [comment]
virer l'entrée dns. reload du dns.
