### ISSUE TITLE
Firefox + Vous [Février 2016]

### ISSUE THREAD

**Issue by pl6025** [mozfr/besogne#69]
La traduction de la lettre d'informations de Firefox du mois de février est ouverte à tous.
Merci d'avance. le pad de brouillon collaboratif est ici, comme d'habitude
https://public.etherpad-mozilla.org/p/FFetV

Voici le planning :
Feb 1: Copy to localizer teams
Feb 12: Localization due
Feb 17-19: Proofs/edits 
Feb 23: Newsletter launches

**Comment by ghost** [comment]
Lettre terminée, prochainement publiée
