### ISSUE TITLE
Traduire le billet sur le virage vers Internet of things

### ISSUE THREAD

**Issue by Flore-mozfr** [mozfr/besogne#7]
Il faudrait rapidement traduire ce billet :

https://blog.mozilla.org/blog/2015/12/09/firefox-os-pivot-to-connected-devices/

Le pad est ouvert : https://public.etherpad-mozilla.org/p/FR-firefox-os-pivot-to-connected-devices

**Comment by SphinxKnight** [comment]
Première relecture effectuée

**Comment by SphinxKnight** [comment]
Le billet est sur dotclear

**Comment by SphinxKnight** [comment]
## Firefox OS se réoriente vers les appareils connectés

_Ce billet est une traduction du [communiqué écrit par Ari Jaaksi](https://blog.mozilla.org/blog/2015/12/09/firefox-os-pivot-to-connected-devices/) quant à la réorientation du projet Firefox OS._

Tout est connecté autour de nous. Cette révolution qui a déjà commencé sera plus importante que toutes les révolutions technologiques que nous avons connues, y compris celle des « smartphones ». L'internet des objets aura un impact fondamental sur nous tous.

À partir d'aujourd'hui, nous construirons des prototypes pour cet avenir. Pour commencer, nous utiliserons les technologies développées au sein du projet Firefox OS.

Pour engager cette exploration, nous arrêterons nos partenariats avec les opérateurs qui portaient sur la construction et l'intégration de smartphones.

Nous allons explorer de nouvelles utilisations d'objets connectés dans la cadre d'un projet open source en gardant en ligne de mire l'intérêt et la satisfaction des utilisateurs.

Nous allons concentrer nos efforts sur les produits et les technologies qui permettent aux personnes d'accéder et de gérer leur univers d'objets connectés en les aidant ainsi à garder le contrôle, la sécurité et l'indépendance de leurs données.

Les défis et les opportunités qui nous attendent sont passionnants. Nous sommes persuadés que le Web peut être la bonne plateforme pour construire l'avenir des objets connectés et nous sommes impatients de partager nos avancées.

**Comment by SphinxKnight** [comment]
Publié ici https://blog.mozfr.org/post/2015/12/Firefox-OS-se-reoriente-vers-les-appareils-connectes

**Comment by Flore-mozfr** [comment]
Merci @SphinxKnight
