### ISSUE TITLE
Collectif Edunathon

### ISSUE THREAD

**Issue by leonarf** [mozfr/besogne#71]
C'est un collectif qui se bat en ce moment contre le "partenariat" de l'éducation nationale avec Microsoft, voir http://www.cnll.fr/news/edunathon-ecole-microsoft/
Est-ce que Mozilla devrait faire partie de ce collectif, ou relayer l'information?

**Comment by pascalchevrel** [comment]
Je ne vois pas Mozilla prendre position là dessus (c'est un accord national, avant qu'ils ne prennent position sur ça, il faudrait qu'ils fassent traduire le contrat, qu'ils payent des juristes locaux pour comprendre le contexte…), par contre je pense que MozFR comme collectif de bénévoles Mozilla francophone pourrait en discuter et s'exprimer publiquement là dessus en son propre nom.

**Comment by TheoChevalier** [comment]
Comme Pascal dit :)
Je rajouterais que c'est peut-être un sujet qui pourrait intéresser Mozilla Advocacy, bien que ce ne soit pas exactement de la politique internet. Tu peux envoyer un message à Reagan McDonald (raegan chez mozilla point com), elle parle français.
Ou sinon, on peut aussi leur proposer d'organiser des évènements au bureau s'ils ont besoin, voir http://mozfr.org/mozillaparis/

**Comment by Ilphrin** [comment]
J'approuve totalement, en tant que communauté francophone on pourrait faire passer un message, par le biais du blog par exemple. :)

**Comment by pascalchevrel** [comment]
Il y a aussi un groupe de travail sur l'éducation chez Mozilla (du côté de Mozilla Foundation) mais je ne suis pas leurs activités et donc leur spectre d'action, il me semble que Goofy et Flore étaient plus impliqués là dedans à une époque.
