### ISSUE TITLE
Traduction de l'AMA d'Ari Jaaksi (Firefox OS)

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#72]
J'ai ouvert un [pad pour la traduction](https://mypads.framapad.org/p/ari-jaaksi-ama-traduction-2b4tq7) de la [session de questions-réponses](https://discourse.mozilla-community.org/t/im-ari-jaaksi-svp-of-connected-devices-ama/6975) donnée par Ari Jaaksi, vice-président senior des appareils connectés (_Connected Devices_) chez Mozilla, vendredi 12 février 2016 de 17 h à 18 h (CET) sur  Mozilla Discourse.

**Comment by Mozinet-fr** [comment]
Le lien a des problèmes. Essayez avec un compte https://mypads.framapad.org .

**Comment by b1venu** [comment]
J'ai créé un compte mais il y a toujours le même problème : `{"error":"BACKEND.ERROR.PERMISSION.UNEXPECTED"}`

**Comment by Mozinet-fr** [comment]
J'avais mis de belles coileurs pour différencier les participants mais elles sont parties dans la migration vers l'instance publique de Mozilla d'Etherpad lite : https://public.etherpad-mozilla.org/p/traduction_de_l'ama_d'Ari_Jaaksi_%28Firefox_OS%29

Amusez-vous bien !

**Comment by Mozinet-fr** [comment]
Merci à tous. https://firefoxos.mozfr.org/post/2016/02/Ari-Jaaksi-Connected-Devices-avenir-de-Firefox-OS
