### ISSUE TITLE
billet de Surman sur le chiffrement - Mozilla et Lets Encrypt

### ISSUE THREAD

**Issue by ghost** [mozfr/besogne#75]
le billet est ici
https://blog.mozilla.org/blog/2016/02/16/help-us-spread-the-word-encryption-matters/

la traduction ouverte à tous est entamée là
https://public.etherpad-mozilla.org/p/Encryption-matters

**Comment by Mozinet-fr** [comment]
La version de la section presse fr n'est pas assez bonne ?

https://blog.mozilla.org/press-fr/2016/02/16/le-chiffrement-ca-compte-aidez-nous-a-precher-la-bonne-parole/

**Comment by ghost** [comment]
Le 2016-02-18 12:30, Mozinet a écrit :

> La version de la section presse fr n'est pas assez bonne ?
> 
> https://blog.mozilla.org/press-fr/2016/02/16/le-chiffrement-ca-compte-aidez-nous-a-precher-la-bonne-parole/
> 
> ah mais c'est simplement que je l'avais ratée :s

désolé, je clos la "besogne"

-- Goofy
