### ISSUE TITLE
Avoir un logo transvision

### ISSUE THREAD

**Issue by Flore-mozfr** [mozfr/besogne#8]
Ce serait sympa d'avoir un logo vraiment trasvision au lieu du petit panda générique.

**Comment by AmarOk1412** [comment]
je poste ça ici : http://wiki.mozfr.org/TODO#Transvision

Il y avait quelques pistes pour commencer le logo.

**Comment by Boboseb** [comment]
Mon ébauche de suggestion
![transvision](https://cloud.githubusercontent.com/assets/4552841/11778762/d14fb760-a256-11e5-8b7f-d02d2e12bc3c.png)
Sachant que je n'ai aucun talent pour faire un vrai logo.

**Comment by pascalchevrel** [comment]
Il nous faut un vrai designer en fait :)

**Comment by Boboseb** [comment]
Clair, mais si on peut déjà lui donner des pistes de ce qu'on veut avoir.

**Comment by Flore-mozfr** [comment]
Bon, @Boboseb est très vexé que je me sois moquée de son dessin...
Donc je suis punie et je dois expliquer ce qu'il avait dans la tête quand il a dessiné ça (ne vous moquez pas !).
Donc l'idée c'est que ce sont des lunettes (absolument évident au premier regard...)... Pardon, on me dit dans l'oreillette "des pince-nez".
 pour évoquer la vision. Avec des sortes de rayons laser (genre vision superman) et une lettre grecque à gauche ainsi qu'un caractère coréen à droite pour évoquer la Transsubstantiation (ou peut-être la transvision en fait)

Voilà, moi j'ai fait ma punition, à vous...

**Comment by ghost** [comment]
Bonjour,

Je suis nouveau ici, actuellement étudiant en designs graphic.

Après avoir lu cette discussion, je n'ai pas tout compris de ce que vous recherchez.
Pouvez-vous m'expliquer cela pour que je puisse aider comme je le peux ?

Merci.

**Comment by pascalchevrel** [comment]
Salut Adrien,

Actuellement Transvision (https://transvision.mozfr.org) n'a pas de logo propre, donc il affiche le logo de mozFR par défaut.

On aimerait avoir un logo distinctif, différent de celui de MozFR, qui puisse être déclinable en favicon mais aussi éventuellement en logo sur un TShirt (par exemple j'aimerais bien faire imprimer une quinzaine de Tshirts pour les contributeurs de Transvision, pour les remercier). Et pourquoi pas un jour des autocollants pour mettre sur son ordi :)

Transvision est une sorte de moteur de recherche pour traducteurs, ça leur permet de retrouver comment une phrase a été traduite dans une langue dans tel ou tel logiciel Mozilla. Idéalement, le logo pourrait refléter cette activité mais ça n'a rien d'obligatoire (d'ailleurs, le renard de Firefox n'a pas grand chose à voir avec le Web).

Pour les couleurs, personnellement je préférerais quelque chose qui ne fasse pas arc en ciel (ne serait-ce que le coût d'impression de T-shirts qui dépend du nombre de couleurs) et qui puisse bien s'intégrer dans le design actuel qui est dans les bleus, ou dans un design futur qui resterait certainement dans des tons froids voire blanc.

Est-ce que ça t'éclaire ?

**Comment by AntoineTurmel** [comment]
Transvision a maintenant son logo :
https://github.com/mozfr/transvision/issues/223
