### ISSUE TITLE
Traduction : Developer support for changes in add-on development

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/besogne#84]
Je vous propose la traduction de cet article pour tech.mozfr.org : 
https://blog.mozilla.org/addons/2016/03/10/developer-support-for-changes-in-add-on-development/

Cet article explique les changements à venir dans le système d'extensions de Firefox et est donc dirigé vers les créateurs d'extensions.

Voici le pad de traduction : https://bimestriel.framapad.org/p/DeveloperSupportAddonChanges

**Comment by TheoChevalier** [comment]
Merci à tous, c'est en ligne https://tech.mozfr.org/post/2016/03/29/Aide-aux-developpeurs-pour-les-changements-a-venir-dans-le-developpement-de-modules
