### ISSUE TITLE
Traduction : How Safe Browsing works in Firefox

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#87]
Je vous propose de traduire  le billet du blog personnel de François Marier (Mozilla) : [How Safe Browsing works in Firefox](https://feeding.cloud.geek.nz/posts/how-safe-browsing-works-in-firefox/) sous licence CC-By-SA 4.0.

Cet article peut paraître ardu avec ses nombreuses préférences cachées de Firefox, mais je pense qu'il est un bon complément de [l'article de SUMO](https://support.mozilla.org/fr/kb/comment-fonctionne-protection-contre-hame%C3%A7onnage-et-logiciels-malveillants) sur le sujet et qu'il présente concrètement dans quel esprit Mozilla met en œuvre le respect de la vie privée dans ses logiciels. L'article intéressera ceux qui veulent protéger finement leur vie privée en ligne et comprendre comment ça marche.

Pad de traduction : https://mypads.framapad.org/p/trad-how-safe-browsing-works-in-firefox-sn5z577b

**Comment by Mozinet-fr** [comment]
Merci à tous ! Le billet est [en ligne sur le blog général](https://blog.mozfr.org/post/2016/04/Comment-fonctionne-blocage-sites-malveillants-Firefox-navigation-securisee).

**Comment by leonarf** [comment]
Il reste 2 petite coquille que j'ai repérée en lisant l'article. Je les note ici en espérant que ce ne soit pas trop tard : 
4 ème paragraphe, il est écrit "Puisque la base de données de le blocage des sites malveillants" : il y a un "le" en trop.
Dernier paragraphe, "wiki de Mozilla sur la blocage des sites malveillants " : la devrait être le.

**Comment by Mozinet-fr** [comment]
Merci du signalement. Il n'est jamais trop tard pour corriger les erreurs. Celles-ci ont échappé à la relecture après le remplacement automatique du nom de la fonctionnalité.
