### ISSUE TITLE
Traduction en anglais de l’interview de Pascal

### ISSUE THREAD

**Issue by TheoChevalier** [mozfr/besogne#92]
Je vous propose de traduire en anglais l’interview de Pascal réalisé par Mozinet en début de semaine : https://blog.mozfr.org/post/2016/06/Passez-a-Nightly-avec-Pascal-Chevrel-pour-avenir-de-Firefox
Cela nous permettra de faire rayonner ces précieuses informations à plus grande échelle que mozfr :)

Ça se passe ici → https://public.etherpad-mozilla.org/p/interview-pascal N’hésitez pas à passer traduire un bout, ou à commencer à réviser.

J’ai directement copié le code markdown pour pouvoir adapter les liens et balises lorsque nécessaire. Je reste joignable sur IRC si vous avez des questions :)

Il y aura peut-être des morceaux spécifiques au français à adapter. Et pour l’extrait du billet de Pascal, la version en anglais est déjà disponible ici : https://www.chevrel.org/carnet/?post/2016/05/19/Let-s-give-Firefox-Nightly-some-love

**Comment by mdartic** [comment]
La traduction semble bien avancée ?

Comment se passe la suite ?

**Comment by TheoChevalier** [comment]
L’interview en français n’a pas eu d’effet sur l’utilisation de Nightly, je ne sais pas encore où on va publier cette traduction et si on va la publier. Pascal nous dira s’il voit une opportunité.

**Comment by mdartic** [comment]
0 effet ? 
pas d'augmentation de download au niveau France c'est ça ?... 
ni d'augmentation des utilisateurs ?

mmm... peut être qu'on pourrait sensibiliser nos entourages respectifs, en bon vieux bouche à oreille ?

**Comment by TheoChevalier** [comment]
> 0 effet ?
> pas d'augmentation de download au niveau France c'est ça ?...
> ni d'augmentation des utilisateurs ?

Pas d’augmentation du taux d’utilisation quotidienne de la version en français :-/

> mmm... peut être qu'on pourrait sensibiliser nos entourages respectifs, en bon vieux bouche à oreille ?

Absolument, c’est tout à fait encouragé d’en parler aux personnes techniques dans notre entourage, que cette traduction soit publiée ou non ;)

**Comment by Mozinet-fr** [comment]
J'ai quelques personnes qui m'ont dit être passées à Nightly. Pas assez pour que ça se voit, à moins qu'ils soient passés sur la VO.

**Comment by SphinxKnight** [comment]
@pascalchevrel @TheoChevalier on clôt ?  (N.B. @lhirlimann disait que lors des évents, "Installer Nightly : vous contribuez à Mozilla" fonctionnait bien)

**Comment by pascalchevrel** [comment]
oui on peut clore
