### ISSUE TITLE
Certificat valide pour bugzilla.frenchmozilla.org

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#94]
Je sais que c'est un problème ancien et ne suis pas sûr que ce soit nécessaire pour notre utilisation actuelle de cette instance de Bugzilla, mais, comme webcompat.com m'a pointé [ce problème](https://webcompat.com/issues/295), je relance la discussion.

Peut-être que Let's Encrypt a changé la donne…

https://bugzilla.frenchmozilla.org/

> La connexion n’est pas sécurisée
> Le certificat n’est valide que pour les noms suivants : bugzilla.ks390239.kimsufi.com, 188.165.242.92
> Code  d’erreur : SEC_ERROR_UNKNOWN_ISSUER

**Comment by mgoessen** [comment]
Salut,

Merci pour le up.

On pourrait,
- Déplacer le bugzilla sur bugzilla.mozfr.org pour profiter de son certificat
- Ou garder le même domaine et générer un certificat lets encrypt (sauf qu'il faut mettre le nez dedans et que ça prend du temps).

Dans les deux cas, ça ne marchera pas avec les URLs de la forme bugnumero1.bugzilla.frenchmozilla.org. Aussi, avant de mettre le nez dedans et de prendre du temps j'aimerais trouver une solution à ce sujet. Il y en a deux:
- payer un certificat wildcard, ce qui ne me semble pas envisageable
- abandonner ces URL, ce que je prefererai faute de solution convenable.

Dans tous les cas, il y a encore des sites, des ml etc à migrer avant.

**Comment by pascalchevrel** [comment]
bugzilla.frenchmozilla.org will be moved to bugzilla.mozfr.org where we have a proper wildcard certificate
