### ISSUE TITLE
Améliorer notre score sur https://observatory.mozilla.org

### ISSUE THREAD

**Issue by pascalchevrel** [mozfr/besogne#95]
On a F sur tous nos sites, il faudrait avoir mieux.

**Comment by pascalchevrel** [comment]
www.mozfr.org: A-

**Comment by pascalchevrel** [comment]
exemple d'entêtes : 
https://github.com/mozfr/www/commit/05837f23aec88bd78effcbc3b6d3b4e1cb63c6a2

**Comment by TheoChevalier** [comment]
https://nightly.mozfr.org A- (https://github.com/mozfr/nightly/commit/1121e897f73e0cf84cbc83663b6099167feb406a)

**Comment by pascalchevrel** [comment]
forum.mozfr.org: B+

**Comment by pascalchevrel** [comment]
planete.mozfr.org: B

**Comment by pascalchevrel** [comment]
blogs: B
