### ISSUE TITLE
Fermer la liste mailman firefoxos

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#97]
Suite à [l'annonce](http://listes.mozfr.org/pipermail/moz-fr/2016-September/008986.html), il faudrait fermer la [liste mailman firefoxos](http://listes.mozfr.org/mailman/listinfo/firefoxos-mozfr).

Merci d'avance.

**Comment by Mozinet-fr** [comment]
Si ça ne pose pas de problème de fermer en écriture et de laisser en lecture seule, ça va, sinon c'est sans regrets.

**Comment by laurentj** [comment]
je n'ai pas trouvé comment juste fermer proprement la mailing list, et tout en laissant les archives accessibles. Les seuls astuces que j'ai trouvé relèvent du bricolage et c'est pas top. On supprime ?

**Comment by lhirlimann** [comment]
J'ai la doc, laisse moi faire celui la, je documenterais dans le ticjets

Le 11 oct. 2016 08:33, "Laurent Jouanneau" notifications@github.com a
écrit :

**Comment by lhirlimann** [comment]
rmlist 'listname' 
ça ferme la liste, si tu ajoute -a ça nuke aussi les archives.

**Comment by Mozinet-fr** [comment]
J'ai du spam régulier, ce serait sympa de fermer ce mailman.

**Comment by lhirlimann** [comment]
root@diplo:/usr/lib/mailman/bin# ./list_lists |grep os
root@diplo:/usr/lib/mailman/bin# ./list_lists         
11 matching mailing lists found:
            Contact - [no description available]
    FirefoxOS-MozFr - Groupe comm Firefox OS de MozFr
               Lyon - [no description available]
            Mailman - [no description available]
             Moz-fr - Communaut� francophone Mozilla
         Mozilla-bf - [no description available]
            Occitan - Traductors e Testaires dels logicials Mozilla en Occitan
             Repsfr - [no description available]
          tupperVim - tupperVim : tous les mois, une soir�e Vimiste � Paris !
       Utilisateurs - Liste d'entraide pour les utilisateurs Geckozone
              Womoz - [no description available]
root@diplo:/usr/lib/mailman/bin# 
root@diplo:/usr/lib/mailman/bin# rmlist FirefoxOS-MozFr 
Not removing archives.  Reinvoke with -a to remove them.
Removing list info
root@diplo:/usr/lib/mailman/bin#

**Comment by Mozinet-fr** [comment]
merci
