### ISSUE TITLE
Rajouter des liens au blog tech

### ISSUE THREAD

**Issue by Mozinet-fr** [mozfr/besogne#99]
Les blogs [principal](https://blog.mozfr.org/) et [Mozilla et la vie publique](https://notreinternet.mozfr.org/) disposent d'une section de menu « Liens » avec les autres blogs et des liens MozFr. Le blog [Bidouilleux d'Web](http://tech.mozfr.org/) n'en a pas.

**Comment by SphinxKnight** [comment]
Fait :)

**Comment by Mozinet-fr** [comment]
Wahoo ! service rapide :)

Le 1er devrait être blog Mozilla francophone et le second lien n'est pas bon.

**Comment by SphinxKnight** [comment]
Damn, je devrais pas faire deux choses en parallèle.
